### ISSUE TITLE
Support for Visual Studio 2015

### ISSUE THREAD

**Issue by ScottIsAFool** [nuproj/nuproj#113]
I noticed in an old issue (for VS2012) that it was mentioned support for 2015 would be coming, was wondering how the progress of that is going?

**Comment by AArnott** [comment]
It's done. I'm just waiting for Immo to publish it. But you can [download it now](https://onedrive.live.com/redir?resid=63d0c265f96e43d%212477835) from my OneDrive.

**Comment by ScottIsAFool** [comment]
Awesome, thanks.
