### ISSUE TITLE
CustomAfterMicrosoftCommonTargets and CustomBeforeMicrosoftCommonTargets should be honored

### ISSUE THREAD

**Issue by AArnott** [nuproj/nuproj#122]
I know NuProj currently doesn't even import Microsoft.Common.targets, but while that's not the case, it's still useful to import these two global properties so that Team Build or other scenarios can work.

**Comment by AArnott** [comment]
Interesting. Evidently NuProj has its own pair of properties: CustomBeforeNuProjTargets and CustomAfterNuProjTargets. I guess that makes sense, and I can workaround the issue by settings these properties based on the other properties since in my case I know it's safe.

**Comment by kovalikp** [comment]
Fixed by #193
