### ISSUE TITLE
Issue executing from nuget package

### ISSUE THREAD

**Issue by scottkoland** [nuproj/nuproj#126]
Hello,

Cool project! I am trying to reference the NuGet package as it will be done on the build server, and am running into an issue.

When I include a reference to the NuProj.0.9.3-beta nuget package and then change my proj file to swap out:

    <NuProjPath Condition=" '$(NuProjPath)' == '' ">$(MSBuildExtensionsPath)\NuProj\</NuProjPath>

With:

    <NuProjPath>$(SolutionDir)\packages\NuProj.0.9.3-beta\tools\</NuProjPath>

I get the following error in Visual Studio 2013 locally and the project will not load or build:

![image](https://cloud.githubusercontent.com/assets/558208/8045147/49956ebe-0de6-11e5-9914-7b967ca7e21a.png)

The stack trace in that file is:

    ===================
    6/8/2015
    Crippling
    System.AggregateException: One or more errors occurred. ---> Microsoft.Assumes+InternalErrorException: The specified default content type (Content) is not defined in the project item schema.
       at Microsoft.Assumes.Fail(String message, Boolean showAssert)
       at Microsoft.VisualStudio.ProjectSystem.Items.ProjectItemSchemaManagerBase.<ComputeCacheDataAsync>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    
The issue seems to be with this line in my project file:

    <Import Project="$(NuProjPath)\NuProj.targets" />

The $(MSBuildExtensionsPath)\NuProj\ and the locally referenced \packages\NuProj.0.9.3-beta\tools\ seem to have identical files, and the pathing is correct.

Any idea why this is happening for me?

Thanks,
Scott

**Comment by GingerBuffalo** [comment]
+1 on this issue. I'm experiencing the exact same problem right now.

**Comment by kovalikp** [comment]
Could not reproduce the error in latest release (0.10.4-beta-gf7fc34e7d8). I've tried both VS 2013 and 2015. Please reopen the issue if you still experience the error.
