### ISSUE TITLE
Don't build ProjectReferences when building inside of Visual Studio

### ISSUE THREAD

**Issue by terrajobst** [nuproj/nuproj#13]
Reported by @aarnott:

> I've been stumped by some build errors/warnings on Solution Rebuild that I've been seeing in solutions that include NuProj. And it finally dawned on me what's going wrong:
> 
> NuProj is building project references when built within Visual Studio.
> 
> It's not obvious, but VS has special build semantics that vary from the command line, and when you're writing your own .targets files you have to be aware of them in order to play well in VS.
> 
> For example, here is the output window contents after a Rebuild of a NuProj with one project reference:
> 
> > 1>------ Rebuild All started: Project: DiffPlex, Configuration: Debug Any CPU ------
> > **1>  DiffPlex -> C:\Users\Andrew\git\diffplex\DiffPlex\bin\Debug\DiffPlex.dll**
> > 2>------ Rebuild All started: Project: DiffPlex.NuGet, Configuration: Debug Any CPU ------
> > **2>  DiffPlex -> C:\Users\Andrew\git\diffplex\DiffPlex\bin\Debug\DiffPlex.dll**
> > 2>  DiffPlex.NuGet -> C:\Users\Andrew\git\diffplex\DiffPlex.NuGet\bin\Debug\DiffPlex.1.2.1.nupkg
> > ========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========
> 
> Notice how `DiffPlex.dll` was rebuilt twice, once for itself and once as part of the NuProj build? That's not supposed to happen. Not only does this slow down the build, it can cause build errors because other projects that also reference `DiffPlex` are building at the same time as `DiffPlex.NuGet` and fail to find the `DiffPlex.dll` because the double-build just deleted it.
> 
> So how to fix this? Well, there are two global properties you can check out in `Microsoft.Common.targets` for ideas of how to handle this: `BuildingInsideVisualStudio` and `BuildProjectReferences`. A project system in VS sets the global property `BuildingInsideVisualStudio=true` to all builds. The `.targets` then translate that to cause `BuildProjectReferences` to default to false. When `BuildProjectReferences` is false, take care to resolve your project references without causing them to actually build.
> 
> I'm not intimately familiar with the details of the `.targets` authoring. By the looks of it, `Microsoft.Common.targets` is anything but simple in its use of these two properties and is probably much more complicated than yours needs to be. If you want more advice in this area, we can loop in Sara Joiner, our resident expert.

**Comment by AArnott** [comment]
This isn't fixed by d62e5af. It still repros.
