### ISSUE TITLE
Add import for .user files

### ISSUE THREAD

**Issue by kovalikp** [nuproj/nuproj#131]
Add following import at appropriate location:
```xml
<Import Project="$(MSBuildProjectFullPath).user" Condition="Exists('$(MSBuildProjectFullPath).user')"/>
```

**Comment by AArnott** [comment]
I'm curious what the scenario is that would benefit from this.

**Comment by kovalikp** [comment]
I need to extend build functionality, but I also want to make sure the changes do not get into source control. For example copy packages to local drive nuget source.

**Comment by AArnott** [comment]
Sounds good.
