### ISSUE TITLE
Incompatible with VS 2015

### ISSUE THREAD

**Issue by endeffects** [nuproj/nuproj#135]
The created NuProjects are incompatible with VS 2015, also the Visual Studio Plugin itself is not supported. Would you please update NuProject with VS 2015 support.

**Comment by kovalikp** [comment]
I've made a build this morning for my company's need from deb555600d668b8390eccbbbebb50075046c0b62 . You can find it here:

https://onedrive.live.com/redir?resid=4042D9F9AC973E28!112&authkey=!AIPONCEUYsQVzEY&ithint=folder%2cnupkg

Hopefully official one will be available soon via standard channels (VS and NuGet galleries).

**Comment by kovalikp** [comment]
See #142 for latest version.

**Comment by JoshuaKGoldberg** [comment]
Is this resolved?

**Comment by kovalikp** [comment]
Yup, we have a official release with VS 2015 support: https://visualstudiogallery.msdn.microsoft.com/fbe9b9b8-34ae-47b5-a751-cb71a16f7e96
