### ISSUE TITLE
Strange msbuild failure, CI,  error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.

### ISSUE THREAD

**Issue by techzilla** [nuproj/nuproj#142]
We've created an example csproj, and a nuproj that references the csproj.  Visual studio builds the correctly without error, a nuget package is generated.   However when I attempt to do this with msbuild, it  Errors on the nuproj.

I've done this many different ways, using msbuild on the sln, the nuproj directly... etc.  This is also all from the same box as the VS, so I'm completely unsure if this is even supposed to be working.

```
...
Done Building Project "C:\CI\example-msbuild-asp45\example-msbuild-asp45\example-msbuild-asp45.csproj" (Build target(s)).


Project "C:\CI\example-msbuild-asp45\example-msbuild-nuget\example-nugetmsbuild.nuproj" (1) is building "C:\CI\example-msbuild-asp45\example-msbuild-asp45\example-msbuild-asp45.csproj" (2:3) on node
1 (_NuProjGetProjectClosure target(s)).
C:\CI\example-msbuild-asp45\example-msbuild-asp45\example-msbuild-asp45.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
Done Building Project "C:\CI\example-msbuild-asp45\example-msbuild-asp45\example-msbuild-asp45.csproj" (_NuProjGetProjectClosure target(s)) -- FAILED.
 
_NuProjGetProjectClosure:
  Build continuing because "ContinueOnError" on the task "MSBuild" is set to "WarnAndContinue".
GetNuProjPackageDependencies:
Skipping target "GetNuProjPackageDependencies" because it has no inputs.
Done Building Project "C:\CI\example-msbuild-asp45\example-msbuild-nuget\example-nugetmsbuild.nuproj" (rebuild target(s)) -- FAILED.
 
 
Build FAILED.
 
"C:\CI\example-msbuild-asp45\example-msbuild-nuget\example-nugetmsbuild.nuproj" (rebuild target) (1) ->
"C:\CI\example-msbuild-asp45\example-msbuild-asp45\example-msbuild-asp45.csproj" (_NuProjGetProjectClosure target) (2:3) ->
  C:\CI\example-msbuild-asp45\example-msbuild-asp45\example-msbuild-asp45.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
```

**Comment by techzilla** [comment]
Trying this again with a fresh master clone.

**Comment by kovalikp** [comment]
I've made a CI build of my dev branch, which is little bit ahead of current nuproj/master. See here: https://ci.appveyor.com/project/kovalikp/nuproj-3rktd/build/artifacts

Installing `NuProj.Common.nupkg` to your `.csproj` projects will resolve the issue.

**Comment by stffabi** [comment]
By injecting the Microsoft.Common.NuProj.targets through CustomAfterMicrosoftCommonTargets parameter, one could completely get rid of NuProj.Common.nupkg and installing it into code projects.

**Comment by kovalikp** [comment]
Using `CustomAfterMicrosoftCommonTargets` was one of our first solutions. Unfortunately this had unforeseen consequences. Please have a look at #120 for further details. That's why we opted to use separate package to inject required targets to .csproj projects for builds, where NuProj cannot be installed.
