### ISSUE TITLE
Content item not packaging in Content folder

### ISSUE THREAD

**Issue by squalrus** [nuproj/nuproj#146]
I have been experimenting with a converted Project as well as a brand new Nuproj Project, and I am not able to get files into a Content folder in the generated .nupkg

I am using the format in the documentation:
```xml
<ItemGroup>
    <Content Include="Readme.txt" />
</ItemGroup>
```

And after building `Readme.txt` is in the root and not in a Content folder.

**Comment by AArnott** [comment]
Content items simply add files to the package. If you want the files in your content folder, create a content folder in the project and put them there.

**Comment by kovalikp** [comment]
I guess docs also need to be updated. Please refer to latest docs here: https://github.com/nuproj/nuproj/blob/master/docs/Authoring.md#packaging-files

**Comment by squalrus** [comment]
Based on the documentation link, a `<TargetPath></TargetPath>` is no longer supported for `<Content>`, as described here: http://nuproj.net/documentation/#packaging-files?

Is there a different way to accomplish what was originally in my nuspec (below) where I can maintain a structure in my source but restructure the output?:
```xml

  <files>
    <file src="less\" target="Content\css\sundog" />
    <file src="js\" target="Content\Scripts\sundog" />
  </files>
```

**Comment by kovalikp** [comment]
This works for build, but causes CPS to crap its pants (if you're using VS extension):
```xml
<Content Include="less\">
  <Link>content\css\sundog</Link>
</Content>
```
Next one works also with VS extension. You can remove `**\` and `%(RecursiveDir)` if you're not using sub-directories. 
```xml
<Content Include="less\**\*.*">
  <Link>content\css\sundog\%(RecursiveDir)%(Filename)%(Extension)</Link>
</Content>
```

I hope this helps.

**Comment by squalrus** [comment]
Yes, thank you! It's working great!
