### ISSUE TITLE
Need ExcludeFromNupkg for ProjectReference

### ISSUE THREAD

**Issue by ankitC** [nuproj/nuproj#149]
I need to be able tos elect which of the files from my project get into a package. As of now, if I specify a ProjectReference, all its references are also being copied into the package, whereas I don't want the references to be copied. I don't have any control over it. 

Ideally, I would like to control if everything goes or nothing goes or selectively have some stuff be included in the package.

**Comment by AArnott** [comment]
I believe ExcludeFromNupkg already works on project references. Have you tried it?
