### ISSUE TITLE
Build for VS12 or VS14 only

### ISSUE THREAD

**Issue by NN---** [nuproj/nuproj#153]
I have only VS2015 and I would like to build without need to install VS2013 .
Currently wixproj requires both builds of VS12 and VS14.
It would be nice to success building only one feature if other is not present.

**Comment by AArnott** [comment]
I doubt that's going to happen. For one thing, I don't know how to get a setup build to allow for missing files. And that would seem to lead to accidentally releasing setup packages that are incomplete.
But if you can find a good way to do it, while guarding against that risk, we may take a PR.

**Comment by NN---** [comment]
@AArnott Actually I compiled from sources just because there is no extension for 2015 in the gallery: https://visualstudiogallery.msdn.microsoft.com/fbe9b9b8-34ae-47b5-a751-cb71a16f7e96
Can you update ?

**Comment by AArnott** [comment]
I wondered if that was why. Yes, I'm trying to help @terrajobst find time to update the VS Gallery. For now, you can get one with VS2015 support from [here](https://onedrive.live.com/redir?resid=63D0C265F96E43D!2533517&authkey=!AK8Zigo9c5V0D48&ithint=folder%2c)

**Comment by NN---** [comment]
I have compiled msi for my own, but I would like to spread a link to VS gallery rather than compile by myself every time.

**Comment by AArnott** [comment]
You can use my link above every time to avoid compiling yourself every time. 
Please don't upload your own build to VS Gallery though. That will likely confuse users as to why there are two, and either yours or ours will forever be leapfrogging instead of having one consistent latest version.

**Comment by NN---** [comment]
@AArnott Sure, I am waiting for the official release.
You can create a project and just give this link in the VS gallery.
