### ISSUE TITLE
Symbols package with sources

### ISSUE THREAD

**Issue by NN---** [nuproj/nuproj#155]
Currently a symbols package is created only with pdb files.
I wish I had a build with source files as well.
Some NuGet servers such as ProGet or SymbolsSource.org serve both as a symbols server and a source server making it possible to debug the sources.

**Comment by kovalikp** [comment]
NuProj already has supporrt for this. Just set `EmbedSourceFiles` and `GenerateSymbolPackage` properties to `True`.

**Comment by NN---** [comment]
Missed it.
I think the configuration properties should be better structured.

General, Symbols.
