### ISSUE TITLE
The NuProj.Common package's .targets file isn't imported for dotnet PCL projects

### ISSUE THREAD

**Issue by AArnott** [nuproj/nuproj#160]
The fix for this should be similar to what I did for [Nerdbank.GitVersioning's nuget package project](https://github.com/AArnott/Nerdbank.GitVersioning/tree/master/src/Nerdbank.GitVersioning.NuGet).

**Comment by dls314** [comment]
Just to confirm -- Is it currently necessary to import the NuProj.Common.targets file in .NET Core *.xproj style projects?

**Comment by AArnott** [comment]
There is no support for xproj. I doubt that you need it anyway since xproj packages itself.
