### ISSUE TITLE
Continuous build

### ISSUE THREAD

**Issue by NN---** [nuproj/nuproj#167]
I see there is continuous build but without 'VSIX' artifact :(
https://ci.appveyor.com/project/terrajobst/nuproj/build/artifacts

Can you make an option to download vsix file ? Thanks.

**Comment by NN---** [comment]
@AArnott Any idea how to display vsix/msi there after build ?

**Comment by kovalikp** [comment]
My setting for build artifacts here https://ci.appveyor.com/project/kovalikp/nuproj are:

Path to artifact | Deployment name
---------------- | ---------------
bin\release\NuProj_Setup.zip | Setup
bin\release\*.nupkg | Packages
bin\raw\*.vsix | Extensions

**Comment by NN---** [comment]
Maybe this is the reason why in this build there are no artifacts https://ci.appveyor.com/project/terrajobst/nuproj/build/artifacts

**Comment by NN---** [comment]
@AArnott Can you configure CI artifacts?
Thanks

**Comment by AArnott** [comment]
No. Only @terrajobst has the permission to configure the build.

**Comment by AArnott** [comment]
@kovalikp If you export the YAML file for appveyor that you use on your CI, and check it into master of this repo, then that should automatically take over @terrajobst's build configuration, allowing us to fix problems such as the artifacts, etc. Can you do that?

**Comment by kovalikp** [comment]
I didn't realize, owner has to explicitly forbid `appveyor.yaml` in the setting. I would probably do this long time ago ;), Let see if it works.

**Comment by kovalikp** [comment]
Here you go: https://ci.appveyor.com/project/terrajobst/nuproj/build/1.0.127/artifacts
