### ISSUE TITLE
NuProj fails the build on the build server

### ISSUE THREAD

**Issue by konste** [nuproj/nuproj#169]
I follow documentation and the package NuProj 0.10.4-beta is installed on both Dev machine and build server.

First, doc says "you need to override the NuProjTargetsPath property". This may be obsolete - property name does not seem right - I cannot find any reference to this name anywhere else. Do you mean "NuProjPath" here?

Second problem is bigger: NuProj.targets tries to execute _NuProjGetProjectClosure target on dependent projects. On dev box it is found through c:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.Targets\ImportAfter\Microsoft.Common.NuProj.targets
On build server this file is not present in magic folder "ImportAfter" and not wired up to the build, so the target _NuProjGetProjectClosure appears undefined! Microsoft.Common.NuProj.targets present in the package Tools folder, but it is not wired up to the build as far as I could see.

How build on the server supposed to work?

Thank you!
Konstantin

**Comment by mthamil** [comment]
I managed to fix this by adding an Import element for Microsoft.Common.NuProj.targets to the csproj file for the projects referenced by the NuProj project.

**Comment by kovalikp** [comment]
Please refer to the https://github.com/nuproj/nuproj/blob/master/docs/Build.md
You need to install NuProj.Common package to your .csproj projects, if you need to build on the machine without NuProj installer.

**Comment by konste** [comment]
That totally explains it, thank you, @kovalikp !
Would be really helpful to update the obsolete chapter of the primary documentation with this new version, otherwise it is really confusing.

**Comment by ravensorb** [comment]
Is there anyone to automate this?

**Comment by kovalikp** [comment]
None that I'm aware of, that would not cause other problems. We need to inject a target into `Microsoft.Common.targets` that would return closure of all referenced projects. We used to pass the path to `NuProj.Common.nuproj` by passing it as property to relevant `MSBuild` task, but this caused duplicate builds and other issues.

**Comment by ravensorb** [comment]
Ok, so installing NuProj.Common did not fix the error on Appveyor.  I am still getting the same message

    C:\projects\xamarin-forms-labs\src\Web\XLabs.Web\XLabs.Web.WP8.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
    Command exited with code 1

This is the line that is in my csproj file

    <Import Project="..\..\..\packages\NuProj.Common.0.10.4-beta\build\NuProj.Common.targets" Condition="Exists('..\..\..\packages\NuProj.Common.0.10.4-beta\build\NuProj.Common.targets')" />

**Comment by kovalikp** [comment]
Have you installed package to every referenced project, even reference of reference?

**Comment by ravensorb** [comment]
yes. Every csproj file in the entire solution is referencing NuProj.common.

The entire solution is here if you are curious (https://github.com/ravensorb/Xamarin-Forms-Labs)

**Comment by kovalikp** [comment]
Sorry, but I don't see it: https://github.com/ravensorb/Xamarin-Forms-Labs/blob/master/src/Web/XLabs.Web/XLabs.Web.WP8.csproj

Note that NuGet UI does not check content of the `.csproj`, only `packages.config` files. It usually happens that NuGet installs the package only into single project, if there are multiple project files in same directory. I'd recommend you to use `project.<ProjectName>.config` files.

**Comment by ravensorb** [comment]
Ok, thats odd - it exists on my dev.  Thats ok, this project is failing too

https://github.com/ravensorb/Xamarin-Forms-Labs/blob/master/src/XLabs.Core/XLabs.Core.csproj - line 83

and as you can see it is in there (and this one does NOT reference the web csproj in any way)

**Comment by ravensorb** [comment]
Interestingly if you look and the package.config for XLabs.Web -- it is actually referenced.  So I am guessing the install didn't actual work in terms of adding the target in the csproj file.

https://github.com/ravensorb/Xamarin-Forms-Labs/blob/master/src/Web/XLabs.Web/packages.config

**Comment by ravensorb** [comment]
Question -- the XLabs.Web project is actually 1 folder with 6 csproj files (one per platform).  Would this cause an issue with installing the NuProj.common package?

**Comment by kovalikp** [comment]
XLabs.Core builds correctly, according appveyor log: https://ci.appveyor.com/project/ravensorb/xamarin-forms-labs/build/1.0.0.8.master#L327

Yeah, install is the issue. But that's problem with NuGet itself:
1. Check packages.config for X.csproj
2. Install package to X.csproj
3. Check packages.config for X.Y.csproj
4. Skip X.Y.csproj because packages.config already contains package

The way around is to use `project.<ProjectName>.config` files (like I mentioned earlier), like here: https://github.com/kovalikp/wcfmef/tree/master/src/ServiceModel.Composition (last two files)

**Comment by ravensorb** [comment]
ahh -- excellent point!  I didn't think about the package.conig issue :)  I just manually added the missing pieces to the csproj file.

Any chance you have a link to the nuget documentation that talks about that work around?  That is a way cool find!

**Comment by kovalikp** [comment]
It was mentioned release notes: https://docs.nuget.org/release-notes/nuget-2.8#individual-packages.config-files-for-different-platforms

But it took me a while to find it and could not find it mention anywhere else.

**Comment by AArnott** [comment]
@ravensorb:

> Now I just need to figure out how to auto-increment the nupkg version

 I hope nerdbank.gitversioning works for you to solve that problem. :)
