### ISSUE TITLE
MSB4184 when referencing Microsoft.Bcl.Build NuGet package

### ISSUE THREAD

**Issue by SamuelMcAravey** [nuproj/nuproj#171]
I ran into a weird issue that I have seen several times. When I reference the Microsoft.Bcl.Build NuGet package in a library that is then referenced by NuProj I get an error: 

*MSB4184 The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.	Test	C:\Program Files (x86)\MSBuild\NuProj\NuProj.targets	432*

Double clicking on the error takes me to line 432, but I am not proficient enough at MSBuild to properly debug this. I ran the MSBuild debugger and walked though the targets file, but I couldn't spot anything obvious.
https://github.com/nuproj/nuproj/blob/master/src/NuProj.Targets/NuProj.targets#L432

Oh, one other note... When I run MSBuild on the solution from the VS developer command line everything builds perfectly. Not sure why... Is Visual Studio doing something weird to the build?

Here is a link to a simple project replicating the issue. Any ideas on what is going on? 
http://1drv.ms/1l4rPFQ

**Comment by AArnott** [comment]
Which version of NuProj are you using? Are the .targets coming from the MSI install or the NuProj nuget package? Which version?

**Comment by SamuelMcAravey** [comment]
For the sample project that I linked to the .targets are coming from the MSI install, but I also see the same error if I use the NuGet package. What's strange is that I get the error only when I try to build inside of Visual Studio, but if I run MSBuild from the command line on the exact same solution, everything builds just fine.

**Versions**
MSI Installer v0.10.4
NuGet: NuProj.0.10.4-beta-gf7fc34e7d8

**Comment by kovalikp** [comment]
Ok, so Microsoft.Bcl.Build overrides `GetTargetPath` target. The new one has condition, that evaluates to `false` when `GetTargetPath` is being called after `*OutputGroup` targets in VS.
