### ISSUE TITLE
Bug: [System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.	

### ISSUE THREAD

**Issue by ravensorb** [nuproj/nuproj#181]
I am getting the following error message when building a nuproj file.  This is a pretty basic project file that contains 6 references to other csproj files (Class Assmeblies, PCL assemblies).  These related projects target multiple platforms (Xamarin Droid, Xamarin iOS, NetCore, Net45, WPA, WPA8).

    Code: MSB4184	
    Message:  The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.	
    File: C:\Program Files (x86)\MSBuild\NuProj\NuProj.targets	
    Line: 432	

I am not sure where to look for more information on what is causing the error.

**Comment by SamuelMcAravey** [comment]
This is the same error I ran into with issue #171

**Comment by ravensorb** [comment]
Exactly the issue I am running into.  I'll close this as a duplicate.
