### ISSUE TITLE
Feature Request: Supporting adding refernces of projects to set dependencies instead of including assemblies in output

### ISSUE THREAD

**Issue by ravensorb** [nuproj/nuproj#182]
Long title :smile: The idea is to have nuproj replace assemblies that are part of referenced projects with a dependency rather than including the dlls files in the final output.  

I believe this is possible by hand editing the nuproj file however that starts to reduce the value of the visual studio build task.

**Comment by ravensorb** [comment]
Ignore this -- I released that I needed to reference the nuproj file instead of the source project

**Comment by AArnott** [comment]
Right you are. :)
