### ISSUE TITLE
Add support for Content V2

### ISSUE THREAD

**Issue by jmelosegui** [nuproj/nuproj#191]
When a Visual Studio project uses a project.json file (instead of package.config), files under content folder of a NuGet package are not copied into the project. It would be nice to have support for [contentFiles](https://docs.nuget.org/Release-Notes/NuGet-3.3#contentfiles) from this project. So we can generate packages with the new [contentFiles folder](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Content-v2-for-project.json) structure.

**Comment by kovalikp** [comment]
Yeah, this look like a important feature we're missing. I'll look into it.

**Comment by kovalikp** [comment]
@AArnott what do you think would be the best way to handle additional metadata for this content in CPS? 

1. Just add `BuildAction` and `CopyToOutput` metadata to `Content` item type.
2. Add new `ContentFile` item type and, and if the file is not in the `contentFiles` sub-directory
  1. throw an error
  2. automatically modify target path (we used to have similar behavior for `Content`, `Build`, `Tools` item types, but this was deprecated in favor of single `Content` type)
3. any better idea?

**Comment by ravensorb** [comment]
Isn't a separate content type needed to allow for unique metadata at the item level?

**Comment by AArnott** [comment]
Having two item types for content seems like it would be confusing. What metadata applies to the new v2 content?

**Comment by kovalikp** [comment]
`buildAction`, `copyToOutput` and `flatten`. `buildAction` and `copyToOutput` directly translate to item properties in consuming project, `flatten` affects path relative to target framework folder.

**Comment by kovalikp** [comment]
Anyway, I'll just add the relevant metadata to `Content` items under `Content File` category. Do we want some special behavior if the user sets those metadata outside `contentFiles` folder (warning, error), or just silently ignore it?

**Comment by ravensorb** [comment]
what not create a separate content type -- that is what they are for :)

**Comment by AArnott** [comment]
My only hesitation is in the question as to whether there really are two content types.
Are they fundamentally different, or should one content type be treated in the new way (automatically)?

**Comment by kovalikp** [comment]
I don't think they are fundamentally different. They are still a file in specific NuGet directory, just with some metadata on top. 

If we would not have CPS, using single `Content` item seem like obvious choice. Adding any item metadata to msbuild script, even that is not recognized by build system, is explicit choice by user. 

In CPS, `buildAction` and other will be present for all `Content`, even if it's outside `contentType` directory. In this case I would expect at least a warning that I used something provided by CPS in wrong way.

Ideally we could dynamically adjust property page, but this is not supported IIRC.

**Comment by ravensorb** [comment]
My understanding is that to "dynamically" adjust the property page we would need another content type -- which is one of the main reasons I am recommending it.  If we do not do this, then we are most likely going to end up with property pages that are very confusing to use and could lead to more errors that anything else (incompatible combinations or missing required settings).

**Comment by kovalikp** [comment]
In that case how should we 
- `ContentFile` outside `contentFiles` directory
- `Content` in `contentFiles` directory
- `Content` with `ContentFile` metadata in/outside `contentFiles` directory

**Comment by ravensorb** [comment]
Would this be even more of a reason for the separate content type as we can provide scope restrictions on where it can exist?

**Comment by kovalikp** [comment]
Not really. Notice the options I mentioned introduce 4 special scenarios to handle, instead of 1 mentioned earlier.

FYI, my WIP implementation does what you suggest. But during processing it just copies `ContentFile` items into `Content` and let `GenerateNuSpec` to handle any medatada accordingly. `ContentFile` is currently just for cosmetic reasons. Keeping them separate would effectively double size of certain targets (e.g. resolving links). That's why I also question necessity of having separate item types.

**Comment by AArnott** [comment]
@kovalikp you can have two item types for the project, but as a step in the build, consolidate to just one to avoid doubling .targets size.

**Comment by kovalikp** [comment]
Yeah, that's what I do now. It just completely blurs the line between `Content` and `ContentFile`, making distinction after the merge between those two moot.

**Comment by AArnott** [comment]
You could add metadata to the merged item type so that you can distinguish them.

**Comment by kovalikp** [comment]
So, two item types it is? Then how to handle the edge cases I mentioned earlier?

1. `ContentFile` outside `contentFiles` directory
  - treat as `Content`
  - correct target path
  - ignore
  - warn/error

2. `Content` in `contentFiles` directory
  - treat as `ContentFile`
  - ignore
  - warn/error

3. `Content` with `ContentFile` metadata in `contentFiles` directory
  - ignore metadata
  - warn/error

4. `Content` with `ContentFile` metadata outside `contentFiles` directory
  - same as 2.
  - same as 2. but ignore metadata

**Comment by AArnott** [comment]
I wouldn't quietly change the semantics of item type based on it being in the 'wrong' path. A build error sounds better to me.
