### ISSUE TITLE
Integration with Appveyor?

### ISSUE THREAD

**Issue by ravensorb** [nuproj/nuproj#194]
I am working on integrating nuproj into an opensource framework (https://github.com/ravensorb/Xamarin-Forms-Labs) and am trying to get the build in appveyor working.  Right now I am running a "pre command" to get nuget to install the package in the packages folder.  However it does not seem to be working - I am getting errors like
 
    C:\projects\xamarin-forms-labs\src\Settings\XLabs.Settings\XLabs.Settings.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
    C:\projects\xamarin-forms-labs\src\Settings\XLabs.Settings.XamSettings\XLabs.Settings.XamSettings.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
    C:\projects\xamarin-forms-labs\src\Web\XLabs.Web\XLabs.Web.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
    C:\projects\xamarin-forms-labs\src\Web\XLabs.Web\XLabs.Web.Droid.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
    C:\projects\xamarin-forms-labs\src\Web\XLabs.Web\XLabs.Web.iOS.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
    C:\projects\xamarin-forms-labs\src\Web\XLabs.Web\XLabs.Web.Net45.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
    C:\projects\xamarin-forms-labs\src\Web\XLabs.Web\XLabs.Web.PortableClient.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
    C:\projects\xamarin-forms-labs\src\Web\XLabs.Web\XLabs.Web.WP8.csproj : error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
    Command exited with code 1

So my question is -- what am I doing wrong :)

Note: The build is working 100% correctly on my local dev env.

**Comment by kovalikp** [comment]
Please see #169.

**Comment by ravensorb** [comment]
thanks -- I thought I searched on this issue and for some reason didn't find that one.
