### ISSUE TITLE
Feature Request: Support For linked files

### ISSUE THREAD

**Issue by ravensorb** [nuproj/nuproj#195]
Would it be possible to add support for "linked" files?

Ideally, I'd like to have a tools folder that contains a link to a powershell script - I'd like to use the same script for all of the packages I create.

**Comment by kovalikp** [comment]
We do: https://github.com/nuproj/nuproj/blob/master/docs/Authoring.md#packaging-files

**Comment by ravensorb** [comment]
tried that -- didn't include the file.

I added it via Visual Studio (add linked file) and I added it directly in the nuproj file -- neither one was put into the resulting package file.

**Comment by kovalikp** [comment]
Can you post fragment of your .nuproj file with those linked files?

**Comment by ravensorb** [comment]
Here is what I tried first (this is what I would like to do)

    <Content Include="..\scripts\install.XLabs.Core.ps1">
        <Link>tools\install.ps1</Link>
    </Content>

Here is the other way I tried

    <Content Include="..\scripts\install.ps1">
        <Link>tools\install.ps1</Link>
    </Content>

**Comment by kovalikp** [comment]
Works On My Machine™. Can you check-in your code in separate branch? I'd have a look.

**Comment by kovalikp** [comment]
Have you managed to get it going?

**Comment by ravensorb** [comment]
I'll post a branch this weekend for you to look at -- still haven't been able to get it working.

**Comment by ravikagit** [comment]
I tried this too, but does not work for me either. I did like:
<Content Include="..\Product\\Deploy\Templates\OctopusDeploy.xml">
		<Link>Content\Deploy\Templates\OctopusDeploy.xml</Link>
	</Content>

did you get it working?

**Comment by Andne** [comment]
Against the last couple builds I've tried - 0.11.14 and 0.11.24 I think - I've been able to add files as linked and have them be properly included in the resulting nupkg file.

**Comment by AArnott** [comment]
Thanks, @Andne
