### ISSUE TITLE
Bug: Path Too Long

### ISSUE THREAD

**Issue by ravensorb** [nuproj/nuproj#198]
There seems to be an issue with Path length related to this property group in NuProj,targets

    <PropertyGroup> 
        <_NonNuProjProjectTargetPath>$([System.IO.Path]::GetDirectoryName($(_NonNuProjProjectTargetPath)))\</_NonNuProjProjectTargetPath>
        <_NonNuProjProjectPath>$([System.IO.Path]::GetDirectoryName(%(_NonNuProjProjectReference.FullPath)))\</_NonNuProjProjectPath>
    </PropertyGroup>

    Severity	Code	Description	Project	File	Line	Suppression State
    Error	MSB4184	The expression "[System.IO.Path]::GetDirectoryName(E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\src\IOC\XLabs.Ioc\bin\Debug\XLabs.Ioc.dll;E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\src\XLabs.Core\bin\Debug\XLabs.Core.dll;E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\src\Platform\XLabs.Platform\bin\Debug\XLabs.Platform.dll;E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\src\Platform\XLabs.Platform.W81\bin\Debug\XLabs.Platform.WinUniversal.dll;E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\src\Platform\XLabs.Platform\bin\Debug\XLabs.Platform.dll;E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\src\Forms\XLabs.Forms\bin\Debug\XLabs.Forms.dll;E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\src\Forms\XLabs.Forms.W81\bin\Debug\XLabs.Forms.W81.dll)" cannot be evaluated. The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.	XLabs.Forms.NuSpec	E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\NuProj.0.10.4-beta-gf7fc34e7d8\tools\NuProj.targets	432

**Comment by AArnott** [comment]
Passing a semicolon-delimited list of paths to `GetDirectoryName` sounds broken anyway. I wonder how this is supposed to ever work. I agree, we should fix it.

**Comment by kovalikp** [comment]
What's the type of the referenced project causing this? I suspect some non-standard project is returning multiple files from `GetTargetPath`.

**Comment by dmalanij** [comment]
I've just experienced this and seem not to be related with non-standard project. I have my solution with bunches of different project types and their packages working fine under VS 2013.  However, same solution opened with VS 2015 fails to build one particular nuproj with this error where all the paths are concatenated with *;* and therefore quickly hitting the 248 characters limitation. I'll try to narrow this down a little bit but at this point I'm suspicious on the new version.

@ravensorb, which version of Visual Studio are you using?

**Comment by kovalikp** [comment]
If you could narrow this to specific project type, I would really appreciate that.

**Comment by se** [comment]
Is there any update about this? @AArnott

**Comment by se** [comment]
Done. Fixed it.

Change your NuProj.targets file line 432 with this;

<_NonNuProjProjectTargetPath>$((_NonNuProjProjectTargetPath.ToString().Split(";") | ForEach-Object { (&amp;{If([String]::IsNullOrEmpty($_)) {$null} Else {[System.IO.Path]::GetDirectoryName($_)}})})\</_NonNuProjProjectTargetPath>

@ravensorb @AArnott

**Comment by kovalikp** [comment]
Do you have a publicly available sample, that could be used to reproduce this bug? @se

**Comment by se** [comment]
You can find it on XLabs repository. https://github.com/XLabs/Xamarin-Forms-Labs

And also you can find fixed version on https://github.com/monocode/monocode-forms. Here the direct link of targets file.

https://github.com/monocode/MonoCode-Forms/blob/master/.nuget/nuproj/tools/NuProj.targets

**Comment by kovalikp** [comment]
I have tried the project with latest targets and assemblies, and it seem that issue was already resolved as a byproduct of commit 94647384. Also I was able to reproduce the bug with old build system.

So I believe no further action is necessary from our side, just update the targets and assemblies in your `.nuget/nuproj` folder.
