### ISSUE TITLE
File ItemGroup behaves different than file in nuspec when recursivly evaluating subfolders

### ISSUE THREAD

**Issue by stephanadler1** [nuproj/nuproj#200]
Applies to nuget package version 0.10.4-beta-gf7fc34e7d8.

Let a, b and c be subdirectories in folder out. When adding an item group like so into the nuproj:

```
  <ItemGroup>
    <File Include="out\**\*">
      <TargetPath>tools</TargetPath>
    </File>
  </ItemGroup>
```

the generated .nuspec file folds all files into tools, instead of adhering to the behavior in Nuget, which places them into their respective subdirectories.

Observed behavior (in the generated nuspec file):

```
<file src="<fullpath>\out\file1" target="tools" />
<file src="<fullpath>\out\a\file1" target="tools" />
<file src="<fullpath>\out\b\file1" target="tools" />
<file src="<fullpath>\out\c\file1" target="tools" />
```
Since the files with the same filenames are place in the same directory, generating the nuget package terminates with "NuProj.0.10.4-beta-gf7fc34e7d8\tools\NuProj.targets(646,5): error : Cannot add part for the specified URI because it is already in the package."

Expected behavior:
```
<file src="<fullpath>\out\file1" target="tools" />
<file src="<fullpath>\out\a\file1" target="tools\a" />
<file src="<fullpath>\out\b\file1" target="tools\b" />
<file src="<fullpath>\out\c\file1" target="tools\c" />

```

**Comment by kovalikp** [comment]
This is normal MSBuild behavior. To get the desired result, you need to use this:
```xml
  <ItemGroup>
    <Content Include="out\**\*">
      <Link>tools\%(RecursiveDir)</Link>
    </Content>
  </ItemGroup>
```
