### ISSUE TITLE
GenerateNuSpec MSBuild task fails with error MSB3073 when git.exe path has a space

### ISSUE THREAD

**Issue by pbalachandar** [nuproj/nuproj#201]
**Git path having space**
E:\Branch\Product\Component\src\Common\CommonNuGet>where git.exe
E:\Program Files\Git\cmd\git.exe
C:\Program Files (x86)\Git\cmd\git.exe
C:\PROGRAM FILES (X86)\GIT\CMD\git.exe

**Below is the build output.**
Target "GenerateNuSpec" in file "E:\NuGetCache\NuProj.1.0.30\NuProj.Targets" from project "E:\Branch\Product\Component\src\Common\CommonNuGet\CommonNuGet.nuproj" (target "CreatePackage" depends on it):
Building target "GenerateNuSpec" completely.
Output file "E:\Branch\Product\Component\src\Common\CommonNuGet\objd\i386\CommonNuGet.nuspec" does not exist.
Task "message"
  REFERENCE=
Done executing task "message".
Task "message"
  FRAMEWORKREFERENCE=
Done executing task "message".
Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Task "Exec"
  git config --get remote.origin.url
  'git' is not recognized as an internal or external command,
  operable program or batch file.
E:\NuGetCache\NuProj.1.0.30\NuProj.Targets(502,5): error MSB3073: The command "git config --get remote.origin.url" exited with code 9009. [E:\Branch\Product\Component\src\Common\CommonNuGet\CommonNuGet.nuproj]
Done executing task "Exec" -- FAILED.
Done building target "GenerateNuSpec" in project "CommonNuGet.nuproj" -- FAILED.
Done Building Project "E:\Branch\Product\Component\src\Common\CommonNuGet\CommonNuGet.nuproj" (default targets) -- FAILED.

**Comment by AArnott** [comment]
There is no NuProj "1.0.30" release. And our NuProj.Targets file doesn't have a `git config --get remote.origin.url` command in it. It appears you're using some forked version of NuProj, so it doesn't seem like an issue with this project.
