### ISSUE TITLE
Generate .nuspec instead of .nupkg

### ISSUE THREAD

**Issue by SamuelMcAravey** [nuproj/nuproj#204]
**Question:** Is it possible and/or what can I do to have NuProj generate only a .nuspec file?

Now for the details: I have been using a now outdated version of NuProj.targets (NuProj.0.10.4-beta-gf7fc34e7d8) for a specific build scenario. Our build server needs to index the source code after build but before creating the NuGet package (this is for source debugging). Because of this I can't use NuProj as-is to manage creating the packages. But with this older version I was able to make some minor edits to NuProj.targets so that it spat out the NuSpec file and didn't create a package. That way I am able to let NuProj do all the heavy lifting of finding dependencies, includes, and so on. 

Any ideas on what I can do? I have been trying for a while to figure out how to modify the latest version of NuProj.targets, but it seems that 94647384d6eb8a741ae36f7806c16f6201cb8e45 introduce enough changes that I am not able to get it to work. Thanks a lot!

**Comment by AArnott** [comment]
Why can't the source indexing happen after the nupkg is created? All the source and symbols are still there.

Is source indexing a part of your build? Or do you really want to *never* create the nupkg?

**Comment by SamuelMcAravey** [comment]
True, but the indexing of the source code replaces the tokens in the PDB files with the locations of the source on the server. Since that happens after build, the nupkg would have been created (with PDBs) before the PDBs get updated by the indexing. As a result we cannot step into the source of the nupkg.

_So yes, source indexing is part of our build, and yes I want to create a nupkg by the time all is said and done._

If it helps here is the actual scenario using the new VSTS build system and our modified version of NuProj:
![image](https://cloud.githubusercontent.com/assets/11021165/13817161/6e8b420c-eb4e-11e5-9ad1-19d711655f17.png)

So we build, test, index, and then we take the .nuspec that was generated by NuProj (modified) and create the nupkg which then includes the indexed pdb files. If there's a better way of going about this I am open to ideas. It just seems that for this type of situation getting a nupkg at build time is too soon.

**Comment by SamuelMcAravey** [comment]
As a side note, I just managed to figure out how to hack the latest version to spit out the .nuspec instead of the .nupkg, but I know it is not reliable. I can show what changes I made, but it would be nice to have a proper way of getting at the nuspec file.

**Comment by kovalikp** [comment]
The `.nuspec` file is produced into `IntermediateOutputPath` (`obj\...` by default). Any reason why can't you reuse that one after the solution builds?

**Comment by SamuelMcAravey** [comment]
Ah, true. The older build I had originally been using a while ago didn't create the obj folder, but the latest one does. So yes, I think I can work with that. Thanks you two.

**Comment by AArnott** [comment]
Great.
