### ISSUE TITLE
$(VersionDependsOn) not honored

### ISSUE THREAD

**Issue by SamuelMcAravey** [nuproj/nuproj#206]
Hi all. I have another issue while trying to move to the latest build of NuProj. I have a sample project which I have attached ([NuProjReferenceTest.zip](https://github.com/nuproj/nuproj/files/178129/NuProjReferenceTest.zip)) and this diagram to illustrate the structure:
![image](https://cloud.githubusercontent.com/assets/11021165/13850639/12bf7cc0-ec18-11e5-8459-d743ce9f2e00.png)

So here is the problem: In ClassLibrary1 I have a file called _NuPkgVersion.targets_ that uses $(VersionDependsOn) to update the .nupkg version to **2.3.4** in the ClassLibrary1.NuGet project. This works great until I add a reference from ClassLibrary2.NuGet to ClassLibrary1.NuGet (red arrow). When I do this I get the following error:
_MSB3030	Could not copy the file "[[some path]]\NuProjReferenceTest\ClassLibrary1.NuGet\obj\Debug\ClassLibrary1.NuGet.1.0.0.nupkg" because it was not found._

So to me this is obvious that it isn't found because ClassLibrary1.NuGet.**2.3.4**.nupkg is on disk and not version **1.0.0**. I have found that the version 1.0.0 comes from the value in the NuGet project properties. Now I am successfully able to override that value with $(VersionDependsOn), but as soon as I start doing this while referencing other NuGet projects it stops looking for the $(VersionDependsOn) for the other projects.

This seems to be a regression since I was able to do this without any issues back on version f7fc34e7. I am trying to upgrade to take advantage of the fixes for projects referencing _Microsoft.Bcl.Build_ (see #171). Any ideas with what is going on? Thanks

**Comment by AArnott** [comment]
Thanks for this great explanation @SamuelMcAravey.
I just hit this myself today and was about to file a bug when I discovered yours. :)

I'm testing a fix right now.

**Comment by AArnott** [comment]
My fix works, from manual testing. I'm preparing a regression test now.
