### ISSUE TITLE
Multiple packages on same solution

### ISSUE THREAD

**Issue by aldinei-sampaio** [nuproj/nuproj#207]
I have a solution with 4 projects and I need to generate NuGet packages for all of them.

The problem is: the projects reference each other, and if I use NuProj to generate the package, the dlls for the referenced projects are included on the package.

When creating packages with "nuget pack projectname.vbproj", I can avoid this problem simply creating a ".nuspec" file on the same folder of each one of the referenced projects. When I do this, NuGet consider them as dependencies on the generated package.

Any way to make the NuProj behave the same way?

**Comment by AArnott** [comment]
Yes. Add project references between the NuProj's themselves that mirror the references between your class libraries.
