### ISSUE TITLE
PackageDirectory doesn't support analyzers

### ISSUE THREAD

**Issue by adrianvmsft** [nuproj/nuproj#208]
In order to use analyzers with project.json, they need to be placed inside an analyzers folder:
https://docs.nuget.org/create/analyzers-conventions

However, PackageDirectory doesn't respect that. That is also confirmed by the documentation:
https://github.com/nuproj/nuproj/blob/master/docs/Authoring.md#using-project-references

**Comment by adrianvmsft** [comment]
The current implementation is very specific, and when it gets wrong, there is no way to override that value. PackageDirectory is represented internally by an enum, and it only allows a limited set of values (https://github.com/nuproj/nuproj/blob/master/src/NuProj.Tasks/PackageDirectory.cs)
I can think of several options:

1. Provide an override mechanism for the TargetPath. This would allow a way to override the calculated value when we get it wrong; it would also accommodate for current limitations (e.g. nuspec features not yet supported by nuproj - e.g. analyzers)

2. Add support for analyzers
Looking at the analyzers documentation, the path logic can get pretty complex. So I guess there is a range of support we could look into between:
  - Minimum: Support only the simple scenarios and rely on the override mechanism for more complex cases
  - Full: Support the full extend of the analyzers path - e.g. support additional properties, like language

Definitely some level of supporting analyzers would be great, but I think Option 1 is still valuable - both short term (to allow analyzers until we add support) as well as long-term .(for potential new features not supported by nuspec)

**Workaround**
Meantime, I am adding the following workaround to my project - (basically a variation of Option 1 that doesn't require changes to the nuproj implementation) - support a new OverrideTargetPath property that when specified on a ProjectReference would override the result of the TargetPath:

```xml
  <ItemGroup>
    <ProjectReference Include="..\Foo.Analyzers.csproj">
      <OverrideTargetPath>analyzers</OverrideTargetPath>
    </ProjectReference>
  </ItemGroup>

 <!-- Overrides the TargetPath calculated by NuProj targets to overcome its limitations(e.g. it doesn't support analyzers)-->
  <Target Name="ProcessFilesWithOverrideTargetPath" DependsOnTargets="ConvertItems" AfterTargets="ConvertItems">
    <ItemGroup>
      <File Include="@(File)" Condition=" '%(File.OverrideTargetPath)' != '' ">
        <TargetPath>%(File.OverrideTargetPath)\%(FileName)%(Extension)</TargetPath>
        <!-- Clearing up the OverrideTargetPath property so that we can easily remove the old items-->
        <OverrideTargetPath />
      </File>
      <File Remove="@(File)" Condition=" '%(File.OverrideTargetPath)' != '' " />
    </ItemGroup>
  </Target>
```

**Comment by kovalikp** [comment]
Added `Analyzers` support to `PackageDirectory` metadata, and also added new `TargetSubdirectory` metadata. To package a csharp analyzer, you can set `PackageDirectory` to "Analyzers" and and `TargetSubdirectory` to "cs". 

If you need absolute control over where to put references, you can set `PackageDirectory` to "Root" and `TargetSubdirectory` to whatever you need.
