### ISSUE TITLE
How to mark a library as supporting WP80 and WPA81?

### ISSUE THREAD

**Issue by ravensorb** [nuproj/nuproj#210]
I have a framework library that supports both WP80 and WPA81 profiles.  NuProj always detects it as WP80 which means that it will not install on projects that are based on WPA81.  Is there a way to tell NuProj to generate the target framework for both?

**Comment by AArnott** [comment]
Is it a portable library? If so, and your targets include both platforms, NuProj should pick up on that automatically.

If it isn't a portable library -- it won't (reliably) work on wpa81, and so NuProj would be correctly excluding that.

**Comment by ravensorb** [comment]
Wouldn't that be dependent on what the library is doing?  There are a fair number things that are supported by both platforms (granted -- there are even more that are not)

**Comment by AArnott** [comment]
If it is doing common things, it can be a portable library, no?
The wpa81 platform does *not* guarantee that it will even load a wp80 assembly from what I hear from my wpa81 owner friends. If it does, you're getting lucky. Anyway, I don't think we'll have NuProj support it as MSFT themselves don't support it on their platform.
