### ISSUE TITLE
Support for contentFiles in nuspec packages

### ISSUE THREAD

**Issue by ravensorb** [nuproj/nuproj#214]
Does nuproj support [contentFiles](http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html)?

If so, awesome!  If not, could this be added?  Ideally we would be able to add a "special folder" called "Content Files", and then under that add a cs/vb/any folder, and then under that add a targetFramework folder and then finally add new/existing files to it. Then on each element set a few key properties like BuildAction, Copy To Output, and Flatten (although the last one only makes sense if we can add wildcard specs for the file name)

**Comment by AArnott** [comment]
Sounds cool.

**Comment by kovalikp** [comment]
I've started working on this some time ago for #191 here: https://github.com/kovalikp/nuproj/tree/feat/contentv2. I should probably finish it some day.

**Comment by kovalikp** [comment]
Resolved by #254
