### ISSUE TITLE
NuProj does not pick up dependencies from project.json powered projects

### ISSUE THREAD

**Issue by maximpashuk** [nuproj/nuproj#215]
Nuget2 supports only packages.config file.
Nuget3 also supports project.json file.

NuProj 0.10.4-beta-gf7fc34e7d8 supports only packages.config file and have no support for project.json file at all.

I have read an article
https://oren.codes/2016/02/08/project-json-all-the-things/

If I modify .csproj to use project.json file instead of packages.config, then linked .nuproj project does not recognize packages lised in project.json.
Resulting .nupkg has no dependencies and this is wrong.

This issue closely related to issue #144

**Comment by AArnott** [comment]
I can't believe we didn't have an active issue for this already. But I totally agree.
As I've switched to project.json for nearly everything already, I've had to add template nuspec files to each of my nuproj's in order to continue to express dependencies in my nupkg's built with NuProj.

**Comment by kovalikp** [comment]
According to [this](https://blogs.msdn.microsoft.com/webdev/2016/05/11/notes-from-the-asp-net-community-standup-may-10-2016/), it appears that `project.json` is being phased.

**Comment by ravensorb** [comment]
Not sure if the article means project.json is being phased out or that is i just slowly becoming the new .csproj format (I think the latter might be the truer statement)

**Comment by AArnott** [comment]
Not quite. That blog post doesn't seem very clear. But I can say project.json isn't going away. It's the DNX flavor of project.json that's going away. The way we use it in msbuild is *not* going away. 
I can't say how closely it will resemble the way it looks today, but project.json as an idea is here to stay, from what I've heard.

**Comment by maximpashuk** [comment]
I can see in master branch some changes related to project.json support.
@AArnott , Is this issue fixed in master branch or not?

**Comment by AArnott** [comment]
No. We don't have a fix for this. The project.json related changes you see are around nuproj itself supporting project.json. Not about supporting it for dependency discovery in other projects.

**Comment by dls314** [comment]
@AArnott when you say `I've had to add template nuspec files to each of my nuproj's in order to continue to express dependencies in my nupkg's built with NuProj`, could you add an example of what you've had to do to make it work to this thread?

**Comment by AArnott** [comment]
Sure, @dls314:
[sample nuspec file](https://github.com/AArnott/IronPigeon/blob/master/src/IronPigeon.NuGet/IronPigeon.nuspec)
[sample reference to it from nuproj](https://github.com/AArnott/IronPigeon/blob/master/src/IronPigeon.NuGet/IronPigeon.NuGet.nuproj#L17)

**Comment by kovalikp** [comment]
@AArnott do you think it's worth to even start working on this? Correct me if I'm wrong but project.json is going to be completely phased out and replaced with full NuGet/MSBuild integration.

**Comment by dls314** [comment]
With https://github.com/onovotny/ReferenceGenerator I think it would be good enough to make sure that NuProj will take dependencies & file mappings from a template *.nuspec file.

**Comment by dls314** [comment]
In which case, project.json and a sibling nuproj project would work

**Comment by AArnott** [comment]
With VS2017's new .NET Core projects (that actually support any target framework -- not just .NET Core) and their new style of PackageReference MSBuild items, I think moving in the direction to better support project.json is a dead direction. And as .NET Core projects even package themselves up, NuProj itself is probably going to become less useful going forward. So I'm closing this since it's unlikely we're going to deliver on it.
