### ISSUE TITLE
Push autobuilds to a nuget feed?

### ISSUE THREAD

**Issue by ravensorb** [nuproj/nuproj#229]
Is there a feed for the auto-builds?  I know there used to be something in myGet, however it looks like that is starting to get stale (hasn't be updated in the last 10 builds I think)

**Comment by AArnott** [comment]
If by 'auto-builds' you're referring to our CI build of master, yes, I push to this feed periodically:

https://www.myget.org/F/aarnott/api/v3/index.json

The last one package pushed is fairly current, I think.

**Comment by ravensorb** [comment]
The last version on that link is .48 and the CI build is .58.

**Comment by AArnott** [comment]
Ah, but if you look at all the changes between 48 and 58, they're all build infrastructural or having to do with the MSI. It's not about additional functionality to the NuGet packages at all.

**Comment by ravensorb** [comment]
Ok, that's good enough for me :)  It just looked like things were out of sync since I have seen a lot of changes around VS 15.
