### ISSUE TITLE
Add Nuget Package support

### ISSUE THREAD

**Issue by sylvainlavoie** [nuproj/nuproj#232]
Since solution level are not supported anymore, it would be nice to have support for Development package in NuProj. That way we can use custom Package to enhance NuProj for our custom need.

I created a Nuget package to change the way the Version is assigned. I need the version from the assemblies and not from the Project file. If I was able to add my package directly to the NuProj I would not have to create custom code to make sure my Nuget Package is installed at build time.

**Comment by AArnott** [comment]
You can. .NuProj now supports project.json, so you can install your package there. That's precisely how I use Nerdbank.GitVersioning to set the nuproj version to be equivalent to the packaged assembly's version.
[Sample](https://github.com/AArnott/ImmutableObjectGraph/tree/master/src/ImmutableObjectGraph.Generation.NuGet)
