### ISSUE TITLE
How to integrate with TeamCity build server?

### ISSUE THREAD

**Issue by stecydube** [nuproj/nuproj#233]
Since the nuproj nuget package is not referenced in any of the projects then the package is not restored on the build server and hence the build fails.

Is there a way to easily integrate this into the TeamCity workflow?

**Comment by ravensorb** [comment]
its a bit of a pain right now.  You can add the nuget package to 1 of the main projects and then manually EDIT each of the nuproj files to reference that folder with something like this -- $(SolutionDir)packages\Nuproj.... 

Ideally there would be a way to keep the nuproj project files auto-updated every time there is a new release of the package (this is not possible right now)

**Comment by stecydube** [comment]
Ok, done that but now MSBuild (on teamcity) shows errors:

```
[MSBuild] proj\Core.NuGet\Core.NuGet.nuproj: Build target: Rebuild
[proj\Core.NuGet\Core.NuGet.nuproj] _NuProjGetProjectClosure
[_NuProjGetProjectClosure] MSBuild
[MSBuild] proj\Core\Core.csproj: Build target: _NuProjGetProjectClosure
[proj\Core\Core.csproj] E:\BuildAgent\work\ea92e323b1a8a633\proj\Core\Core.csproj error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
[MSBuild] Build continuing because "ContinueOnError" on the task "MSBuild" is set to "WarnAndContinue".
[proj\Core.NuGet\Core.NuGet.nuproj] GetNuProjPackageDependencies
[GetNuProjPackageDependencies] Skipping target "GetNuProjPackageDependencies" because it has no inputs.
[proj\Core.NuGet\Core.NuGet.nuproj] ExpandProjectReferences
[ExpandProjectReferences] MSBuild
[MSBuild] proj\Core\Core.csproj: Build targets: BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies
[proj\Core\Core.csproj] Project proj\Core\Core.csproj failed.

```

**Comment by kovalikp** [comment]
You need to install package `NuProj.Common` to your .csproj projects.

**Comment by stecydube** [comment]
I have nuproj and nuproj.common added. No success.

However, if I install the nuproj.msi on the teamcity agent then it works!

Seems to be hardcoded on finding the nuproj targets file in the MSBuild folder...

**Comment by ravensorb** [comment]
how did you edit the nuproj file?  I ask because I have this working on Appveyor and on Visual Studio online without issue.

**Comment by AArnott** [comment]
Installing the MSI makes installing nuproj.common unnecessary. So odds are your install of nuproj.common didn't succeed somewhere or was missed. You need it in every project that your nuproj references, *transitively*.

**Comment by AArnott** [comment]
I don't have to add the NuProj package to my other projects any more. I add it to my nuproj project's own project.json file. Then I modify my nuproj slightly to get the .targets and .props files from that nuget package. Works pretty well for me.

**Comment by stecydube** [comment]
Ok, I've uninstalled nuproj.msi on the build server.
Removed nuget package nuproj from all projects.
Added nuproj.common to "Core" project and not the "Core.Nuget" project.
The build server now complains with this error:
   **The imported project "C:\Program Files (x86)\MSBuild\NuProj\NuProj.targets" was not found.**

I have the following set up in my nuproj file:
```
  <PropertyGroup>
    <NuProjPath Condition=" '$(NuProjPath)' == '' ">$(MSBuildExtensionsPath)\NuProj\</NuProjPath>
  </PropertyGroup>
```

I'm pretty sure I need to modify this but I'm not certain on what to replace this with.

**Comment by AArnott** [comment]
If you're using packages.config to bring in the NuProj package to your solution, use a path like this:

```xml
 <PropertyGroup>
    <NuProjPath Condition=" '$(NuProjPath)' == '' ">..\Packages\NuProj.0.x.y\tools\</NuProjPath>
 </PropertyGroup>
```

But if you're using project.json, use a path like this:
```xml
 <PropertyGroup>
    <NuProjPath Condition=" '$(NuProjPath)' == '' ">$(UserProfile)\NuProj\0.x.y\tools\</NuProjPath>
 </PropertyGroup>
```

**Comment by stecydube** [comment]
Works now. But it's a pain to configure, even more when there will be another release of the nuproj package.
Well, at least now the producing of nuget packages is a lot easier now!
Thanks a lot!

Let's hope microsoft starts noticing this project and includes it in visual studio.
