### ISSUE TITLE
NuProj should not copy dependency DLLs as loose files into the NuProj's own bin folder

### ISSUE THREAD

**Issue by AArnott** [nuproj/nuproj#239]
When packaging up a csproj that has several assembly dependencies, it's good that a NuProj would package up those dependencies, but not good that (from what I'm seeing) it also copies those DLLs into the folder next to the nupkg.

**Comment by kovalikp** [comment]
I've tried this but could not reproduce the issue. In case you still experience the problem with latest version, please reopen this and I'll investigate further.
