### ISSUE TITLE
Missing (possibly on documentation) in order to exclude packages

### ISSUE THREAD

**Issue by petero-dk** [nuproj/nuproj#243]
I have a couple of packages I only use during build, however NuProj picks these packages up and makes them dependencies to my NuGet Packages. Which I do not want to.

I cannot seem to find a way to exclude certain packages to be included.

**Comment by AArnott** [comment]
It sounds like you're using packages as development dependencies. Are you using packages.config and missing a `developmentDependency="true"` attribute on that dependency?

for example:

```xml
<package id="MicroBuild.Teams.Project" version="1.0.104-rc" targetFramework="net451" developmentDependency="true" />
```

**Comment by petero-dk** [comment]
Of course!
