### ISSUE TITLE
A stable release of a package should not have on a prerelease dependency

### ISSUE THREAD

**Issue by KirillOsenkov** [nuproj/nuproj#244]
Since NuProj.Common is a pre-release package, adding that to my solution results in an error produced by my NuProj project:

A stable release of a package should not have on a prerelease dependency. Either modify the version spec of dependency "NuProj.Common (≥ 0.10.4-beta)" or update the version field.	

C:\Users\Kirill\.nuget\packages\NuProj\0.10.48-beta-gea4a31bbc5\tools\NuProj.targets	525	

How do we deal with that?

**Comment by KirillOsenkov** [comment]
I've set isDevelopmentDependency on my NuProj.Common and it seems to do the trick:
```
<package id="NuProj.Common" version="0.10.4-beta" targetFramework="net452" isDevelopmentDependency="true" />
```

Please confirm that this is the recommended solution. Thanks!

**Comment by kovalikp** [comment]
Yes, this is the correct way to do it. NuProj follows NuGet convention for ignoring dependencies as defined in [NuGet documentation](http://docs.nuget.org/consume/command-line-reference#excluding-development-dependencies-when-creating-packages). It is probably worth mentioning in our docs, too.

**Comment by bugged84** [comment]
What if the dependency is not for development purposes, and I want my stable package to use a prerelease dependency for some reason? Why is NuProj enforcing such a rule instead of just doing what its told?

**Comment by kovalikp** [comment]
This is not enforced by NuProj, but by NuGet itself. You can try it for yourself. Just craft your `nuspec` by hand and try to pack it by `NuGet.exe`.
