### ISSUE TITLE
A simple way to exclude a file from the Nuget package

### ISSUE THREAD

**Issue by KirillOsenkov** [nuproj/nuproj#245]
It may happen that a rogue .dll file is included in the generated NuPkg because it's an implicit indirect dependency of another .dll (that's not included in any of the NuGet packages). For instance your .nuproj is referencing a .csproj that uses Roslyn. That project uses Roslyn from a Roslyn NuGet. Roslyn uses MSBuild (it relies on Microsoft.Build.Engine.dll being in the GAC) but doesn't declare this anywhere in the Roslyn package. So Microsoft.Build.Engine.dll ends up being added to my package. Which I don't want of course.

I've found a way to exclude this file from the package: specify this in the .nuproj:

```
  <ItemGroup>
    <_FileDependencyTargetPath Include="Microsoft.Build.Engine.dll" />
    <_FileDependencyTargetPath Include="Microsoft.Build.Framework.dll" />
    <_FileDependencyTargetPath Include="Microsoft.Build.Tasks.Core.dll" />
    <_FileDependencyTargetPath Include="Microsoft.Build.Utilities.Core.dll" />
  </ItemGroup>
```

This ensures that the files get excluded by this line:
https://github.com/nuproj/nuproj/blob/master/src/NuProj.Targets/NuProj.targets#L596

However it would be nice to have a special item type that is specifically designed to let you exclude files from the package, such as ExcludeFromNuGet or something.

**Comment by KirillOsenkov** [comment]
Along the same lines, what's the best way to exclude a package from the Dependencies?

I want to exclude NuProj.Common.

**Comment by AArnott** [comment]
Is this NuProj.Common exclusion still an issue, or did your `developmentDependency="true"` attribute fix that (I expect it did).
As for excluding specific files, we do have an `ExcludeFromNuPkg` metadata you can add to references. Although when it's a case of transitive dependency and there's no reference to add that to, perhaps there's a scenario there to cover.

**Comment by KirillOsenkov** [comment]
developmentDependency="true" fixed the NuProj.Common issue for me.

However I do think that you need an item type to exclude packages that were added from transitive dependencies.

**Comment by kovalikp** [comment]
It's possible to modify behavior by setting `PackageOutputGroups` metadata of project references by excluding unwanted output  groups like `BuiltProjectOutputGroupDependencies` and so. You can see list of all default collected output groups in `NuProj.props`.

**Comment by kovalikp** [comment]
Updated Authoring.md documentation. I hope this is sufficient.
