### ISSUE TITLE
Using .nuproj on a CI server

### ISSUE THREAD

**Issue by KirillOsenkov** [nuproj/nuproj#246]
I have a .nuproj that references a normal .csproj, which in turn has a packages.config with the below reference:

```
  <package id="NuProj.Common" version="0.10.4-beta" targetFramework="net452" isDevelopmentDependency="true" />
```

When I restore packages and build the solution on the CI server (VSTS), I get this error:
```
##[error]Library\Library.csproj(0,0): Error MSB4057: The target "_NuProjGetProjectClosure" does not exist in the project.
```

I understand that I somehow need to add NuProj.Common.targets to that project. Do I do that manually? Just restoring from packages.config isn't enough?

It would be nice to have some docs around setting up the CI server with NuProj. I see that when you install NuProj extension it references NuProj from a Program Files location. But that doesn't work for the CI server.

**Comment by KirillOsenkov** [comment]
Yes, adding it manually seems to have helped. Also it's `developmentDependency`, not `isDevelopmentDependency`, my mistake.

**Comment by KirillOsenkov** [comment]
To clarify, everything is working well, it's just I've added the package.config manually and I missed the step that NuGet would usually do for me (add the import to the .csproj). Not sure if it's worth documenting (how likely are people to manually add the package to packages.config and forget to add the import?).

**Comment by AArnott** [comment]
I'm not sure it's worth documenting. Adding a line to packages.config does *almost* nothing. I think almost everyone expects when using packages.config that they either need to install it with the VS extension or that they'll have more manual work to do.
