### ISSUE TITLE
Is NuGet.Core now required?

### ISSUE THREAD

**Issue by MichelZ** [nuproj/nuproj#250]
Since updating to the latest version (0.11.12-beta), we get this during TFS build.

```
src\packages\NuProj.0.11.12-beta\tools\NuProj.targets (367, 9)
The "AssignTargetFramework" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Core, Version=2.11.1.812, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet.Core, Version=2.11.1.812, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
at NuProj.Tasks.Extensions.GetShortFrameworkName(FrameworkName frameworkName)
at NuProj.Tasks.AssignTargetFramework.ConvertToPackageFile(ITaskItem output) in C:\projects\nuproj\src\NuProj.Tasks\AssignTargetFramework.cs:line 48
at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at NuProj.Tasks.AssignTargetFramework.Execute() in C:\projects\nuproj\src\NuProj.Tasks\AssignTargetFramework.cs:line 31
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]. 
```

**Comment by AArnott** [comment]
@kovalikp could this be a regression from a recent PR you took?

**Comment by kovalikp** [comment]
Nope. I've built  6619e0c1 and it also does not include the missing files. Actually, are missing couple files in the package:
- `NuGet.exe` is explicitly inluded in the `NuProj.nuspec`, but nuget does not package it for some reason.
- `NuGet.Core.dll` and `Microsoft.Web.XmlTransform.dll` do not show in `NuProj.nuspec` at all. 

Preliminary examination suggest this is a problem with how do we handle project references. For some reason `NuProj.Tasks.csproj` lists it as a project output, but with both `CopyLocal` and `Private` set to `false`. This means that `ExpandProjectReferences` target filters them out, and will not be package.

**Comment by kovalikp** [comment]
This looks like an issue related to switching to `project.json`. We have a test that uses packages.config (Dependency_Tools_IsNotFiltered) for same scenario that behaves as expected.

**Comment by jmelosegui** [comment]
Hi @kovalikp. What is the tool you used to generate that image?

**Comment by kovalikp** [comment]
@jmelosegui  https://github.com/KirillOsenkov/MSBuildStructuredLog

**Comment by kovalikp** [comment]
Great, even when I fix generating .nuspec, NuGet.exe seem to implicitly ignore anything coming from nuget packages cache. :sob:

**Comment by kovalikp** [comment]
@AArnott please review and merge, if ok. When you release new package, I think you should unlist the current one.

**Comment by AArnott** [comment]
> Setting NoDefaultExcludes to true fixes the issue. 

This has bit me and others so many times. What do you think of (in a separate change) changing the default for `NoDefaultExcludes` to true in nuproj.props?

**Comment by kovalikp** [comment]
Sounds reasonable, since we do not use wildcards by default and list every file explicitly. MSBuild has a its own mechanism how to exclude files if user requires so.

**Comment by AArnott** [comment]
@MichelZ Can you please confirm that the nuget packages and/or MSI [built here](https://ci.appveyor.com/project/terrajobst/nuproj/build/artifacts) resolve the issue?

**Comment by kovalikp** [comment]
:shipit: I just successfully tested it our TFS build server.

**Comment by AArnott** [comment]
done.

**Comment by MichelZ** [comment]
Thanks all! Will try this when I get some spare time :)  :+1:
