### ISSUE TITLE
NuProj targets could warn when NoDefaultExcludes may be needed

### ISSUE THREAD

**Issue by dls314** [nuproj/nuproj#256]
When the generated nuspec's file list includes a src attribute containing directories beginning with a dot, the NuProj target could warn that NoDefaultExcludes may be needed.

Alternately, NoDefaultExcludes could be defaulted to True

The error shown here is "Cannot create a package that has no dependencies nor content." which doesn't explain how to fix things.

**Comment by kovalikp** [comment]
Changed the default value to true in b0914238.
