### ISSUE TITLE
NuProj fails on MSBuild 14.0 and above

### ISSUE THREAD

**Issue by jeffkl** [nuproj/nuproj#257]
On a machine with only MSBuild 14.0, I get this error:

```
error MSB4062: The "Microsoft.Build.Tasks.AssignProjectConfiguration" task could not be
loaded from the assembly Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. Could not load file or assembly 'Micr
osoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specif
ied. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class t
hat implements Microsoft.Build.Framework.ITask.
```

It looks like [these lines](https://github.com/nuproj/nuproj/blob/master/src/NuProj.Targets/NuProj.targets#L176-L177) mean NuProj will only work if MSBuild 12.0 is installed?

In MSBuild 14.0 they've renamed `Microsoft.Build.Tasks.v12.0.dll` to `Microsoft.Build.Tasks.Core.dll`.  So I'd like to update this .targets file to have logic similar to [this](https://github.com/MobileEssentials/MSBuilder/blob/master/src/CodeTaskAssembly/build/MSBuilder.CodeTaskAssembly.props).  This will also ensure it works with all versions going forward.

See [my fork](https://github.com/nuproj/nuproj/compare/master...jeffkl:dev/jeffkl/msbuild14?expand=1) for the change I'm proposing.  It worked on my machine but I was also wondering if the unit tests would prove it doesn't break anything?  Glancing at them it looks like its covering this kind of change to the .targets.

Thanks

**Comment by AArnott** [comment]
NuProj formally supports MSBuild 12 and VS2013 still. But perhaps it's time to give that up.

**Comment by jeffkl** [comment]
I'm not looking to remove support for MSBuild 12.0, only add support for MSBuild 14.0+.  I've built using MSBuild 4.0, 12.0, and 14.0 and get this output in the MSBuild log:

`Using "AssignProjectConfiguration" task from assembly "Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".`

`Using "AssignProjectConfiguration" task from assembly "Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".`

`Using "AssignProjectConfiguration" task from assembly "Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".`

Technically there is also an MSBuild 11.0 (VS 2012) which it will work with as well.

**Comment by kovalikp** [comment]
Do we want to support multiple versions of MSBuild? I suppose we could build multiple versions of `NuProj.Tasks` put them to appropriate folders (package/install) and adjust `NuProj.targets` accordingly. I'm in favor of doing so.

**Comment by jeffkl** [comment]
NuProj already supports multiple versions of MSBuild.  There's a Visual Studio Extension for 2013 (MSBuild 12.0), 2015 (MSBuild 14.0) and dev15 (MSBuild 15.0).  The `NuProj.msi` also installs itself to all MSBuild versions:

```
C:\Program Files (x86)\MSBuild\12.0\Microsoft.Common.Targets\ImportAfter\Microsoft.Common.NuProj.targets
C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.Targets\ImportAfter\Microsoft.Common.NuProj.targets
C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.Targets\ImportAfter\Microsoft.Common.NuProj.targets
```

The `NuProj.Tasks.dll` is compiled against MSBuild 12.0 but all versions of MSBuild ship with an `MSBuild.exe.config` that redirects all MSBuild assembly versions to that version.  So MSBuild.exe 14.0 redirects versions 0.0.0.0-99.9.9.9 to version 14.0. 

``` xml
<dependentAssembly>
    <assemblyIdentity name="Microsoft.Build" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
    <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
</dependentAssembly>
```

From my testing, the only thing that doesn't work is the `<UsingTask />` which only accounts for 2 versions of MSBuild.  So my change is really just bringing more parity to what is already supported.

In my opinion, I wouldn't bother generating different versions of the Task.dll.  The only case where it will be broken is if a different application is loading the MSBuild object model and that application does not have the assembly redirects in it's application config.  This case is rare and the people who do hit it are used to including a redirect in their app config.

**Comment by kovalikp** [comment]
The `NuProj.Tasks` assembly depends on `Microsoft.Build.Utilities.v12.0`, which does not have corresponding binding redirect. Unfortunately I don't have an environment I could test, if this is an issue.

**Comment by jeffkl** [comment]
Thanks for pointing that out.  This could be a reason to do different versions however NuProj is currently getting around this because it includes `Microsoft.Build.Framework.dll` and `Microsoft.Build.Utilities.v12.0.dll` in the NuGet package.

![image](https://cloud.githubusercontent.com/assets/17556515/17780960/21502b3a-6522-11e6-9bc6-a26ebdf4bd64.png)

I have a clean installed Windows 10 VM with just Git and a non-installed MSBuild for testing this.  I can try more scenarios if you'd like.

**Comment by kovalikp** [comment]
Yeah, I completely forgot NuProj inculdes those dependencies into package by dogfooding itself. But, out of curiosity, could you test if the VS extension (NuProj.msi) works?

**Comment by jeffkl** [comment]
Sure, just to be clear you want a machine with *only* Visual Studio 2015 and NuProj.msi and verify that NuGet projects work?

**Comment by kovalikp** [comment]
Yes

**Comment by jeffkl** [comment]
Okay so this is interesting.  When you install Visual Studio 2015, it installs MSBuild 14.0 *and* MSBuild 12.0.  This is because MSBuild renamed Microsoft.Build.Tasks.v12.0.dll to Microsoft.Build.Tasks.Core.dll.  Since assembly redirection wouldn't work, the team opted to install 12.0 assemblies even when you're installing 14.0.

This explains why I'm the first customer to hit this as I was attempting to build on a machine without any version of MSBuild installed.  The MSBuild team for version 15.0 is not going to be install MSBuild 12.0 assemblies so machines with only Visual Studio "15" would technically not work with NuProj (or other tasks compiled against MSBuild 12.0).  Except the NuGet package contains the required DLLs so at the moment everything is fine.

My change will unblock my scenario but there would need to be another change to compile the task assembly against 12.0 and 14.0.  It would probably also be best to remove the MSBuild assemblies from the package at that time.

**Comment by kovalikp** [comment]
Thanks a lot. Please create a pull request with change you proposed and I'll merge it in. We will probably need to review referenced assemblies once we start working on full VS "15" support, and if we want to keep backward compatibility with 2013/2015.
