### ISSUE TITLE
Error : don't work

### ISSUE THREAD

**Issue by auriou** [nuproj/nuproj#258]
Hello , it's good principle, but with me it does not work . When I add a reference there is a yellow warning icon , and then when I add another reference there is an error message . I use Visual studio 2015 enterprise update 3

![errornuget](https://cloud.githubusercontent.com/assets/1873587/17804543/652aa9fe-65fc-11e6-861d-e403a4ed8efd.png)

And don't work with project .net core the output lib >   netstandard1.5   ... netstandard1.6

**Comment by AArnott** [comment]
NuProj doesn't support netstandard libraries yet.
The error dialog you see comes from a bug in CPS. We can't do anything about it AFAIK.
