### ISSUE TITLE
Content include with globbing path results in failure to complete loading

### ISSUE THREAD

**Issue by dls314** [nuproj/nuproj#260]
If I use a content element in my nuproj file similar to the following, when I load the solution in VS 2015 update 3, the project seems to get stuck in loading. That is, the project name in the solution explorer has a `(loading...)` suffix and the project's tree view in the solution explorer shows only a single untyped file node with the text `This project is still loading...`

```
    <Content Include="..\MyLibrary\bin\$(Configuration)\net45\MyLibrary.*">
      <Link>lib\net45</Link>
    </Content>
```

Any other similar experiences? Workarounds?

**Comment by AArnott** [comment]
Having your project evaluation depend on build outputs like this seems highly suspect. I doubt it would do what you want even during build at the command line. If you _must_ include content like this from your own bin folder, you should move this to an `<ItemGroup>` defined inside of a `<Target>` that executes after the files are placed there, but before NuProj actually packages up files.

**Comment by dls314** [comment]
I was trying to find a way to use NuProj to package .NET Core projects that use the *.xproj project format. I think I'm going to give up on this direction, so I'll close this issue.

For what it's worth, it works for non-globbing paths.

**Comment by kovalikp** [comment]
Even when you use `Link`, every file must represent a single item. This might work for globbing paths:
```
<Content Include="..\MyLibrary\bin\$(Configuration)\net45\MyLibrary.*">
  <Link>lib\net45\%(Filename)%(Extension)</Link>
</Content>
```
Regarding the .xproj, that that file type is going to be obsoleted. So I don't think will support it. Regarding the new .NET Core libraries, I plan to start working on them once SDK gets more mature.

**Comment by dls314** [comment]
@kovalikp That answer works. Also works with RecursiveDir to spec the TFM. Thanks!

**Comment by AArnott** [comment]
I'm (somewhat) surprised to hear you'd want to use nuproj with xproj projects, considering xproj can package itself.

**Comment by dls314** [comment]
The .NET Core tooling is kind of a hot mess from my perspective.

I'm using .NET Core targeting xproj projects mostly because of the warning-style language language in the docs here: https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/target-dotnetcore-with-msbuild against working with .NET Core targeting csproj & project json projects.

Since I'm building it all in a pipeline that uses other MSBuild parts, I need a way to build NuGet packages that works with MSBuild.

If I don't use NuProj, I end up writing something mostly the same that calls "dotnet pack" instead of "nuget pack"

So if NuProj can work (and it can, there are just non-auto parts), I'll use it.

**Comment by dls314** [comment]
From other projects you've linked to, I gather that you're targeting .NET Core using the csproj & project json PCL approach.

Is that working well? Do you feel like the warnings in the dotnet docs are overblown.

**Comment by AArnott** [comment]
I don't target .NET Core itself. The preview SDK is too buggy. And I avoid 'dotnet' CLI for now as well for similar reasons as you.
Instead, I just target profile111 or profile259, which is .NET Core compatible. That works great, so long as you can live with the reduced API surface area. Which I am so far sufficiently motivated to do, to avoid all the .NET Core SDK unpleasantness. 
That said, I hadn't come across the page you linked to that expresses how to do it properly. So I may give it a go. :smile:

**Comment by dls314** [comment]
Instead of the <ItemGroup> defined inside of a <Target> as you suggested above (and I only mostly understood--I'm only semi-literate in MSBuild, I'm just marking the project dependencies in VS so that the xproj builds before the nuproj; seems to work even if the VS solution explorer doesn't look quite right.

**Comment by dls314** [comment]
I tried adding NuProj.Common to the xproj project and referencing its target file manually, but the paths it generated as it tried to find the xproj outputs were a little wacky, so I gave up on auto-finding dependencies for now.
