### ISSUE TITLE
Support for Dev15 (Visual Studio 2017)

### ISSUE THREAD

**Issue by AArnott** [nuproj/nuproj#266]

**Comment by Dany-R** [comment]
I identified a possible problem in `NuProj.ProjectSystem.15/source.extension.vsixmanifest `:
The line
 `<Dependency Id="Microsoft.VisualStudio.MPF.15.0" DisplayName="Visual Studio MPF 15.0" d:Source="Installed" Version="[15.0,15.0)" />`
 should have a Version attribute of `"[15.0,16.0)"` (**16** instead of **15** as upper excluded boundary).

I did not test it but wanted to let you know ;)

**Comment by Dany-R** [comment]
Oh, and for the installation, the path to the IDE directory has changed:

old: `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE"`
new: `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\"`

But still, I don't get it to work with VS2017 RC3.

**Comment by AArnott** [comment]
Thanks, @Dany-R. Regarding the path for installation, it isn't always that path. For example Community SKU would default to a different location. But the real trick is that someone can install VS multiple times to distinct locations now (a new feature in VS2017) which complicates the job of MSI installers for VS extensions.

**Comment by mfidemraizer** [comment]
Hey! Any updates on this? I'm migrating my project [TrackerDog](https://github.com/mfidemraizer/trackerdog) to distribute it as a .NET Standard library, and I had to switch to VS 2017 RC to work on this.

Currently it's already migrated but I'd like to publish it to NuGet, and VS2015 solution was using NuProj...

Thank you in advance!

**Comment by michaelkollmann** [comment]
VS2017 will go RTM on March 7th. 

How is the progress on supporting the new VS release? I'd like to switch to VS2017 as fast as possible, the only thing that will be missing then is .nuproj support.

**Comment by mfidemraizer** [comment]
@michaelkollmann  Maybe the maintainers have lost interest on going further with NuProj because VS2017 has already a new project property section to create its NuGet package [during project's build](https://docs.microsoft.com/en-us/nuget/guides/create-net-standard-packages-vs2017). 

BTW, AFAIK this only applies to .NET Standard class libraries...

**Comment by AArnott** [comment]
I'm nearly done with VS 2017 support. And nuproj offers enough unique functionality that the new project type in 2017 doesn't have that it's worth taking forward. However,  nuproj is quite out of date with respect to .netstandard support and the NuGet team is working on the successor to nuproj and they're reportedly close to completion. When they do finish, if they delivery everything nuproj does, we'll shutter this project.

**Comment by kovalikp** [comment]
The issue here is that VS2017 RC3 does not appear to write `SOFTWARE\Microsoft\VisualStudio\15.0\Setup\VS` registry node. Values there are being used to locate extension directory by WiX VS extension that we use. I don't know if this behavior will change in RTM. But currently we don't have reliable way to determine correct installation directory for VS2017 extension. @AArnott do you have any info if this behavior will change in the RTM? What would be the proper way to determine extension dir?

**Comment by beufordy3k** [comment]
You need the setup configuration api as used by these samples to get the installation location, https://github.com/microsoft/vs-setup-samples

**Comment by kovalikp** [comment]
I'm working on NuProj extension that does not require `.msi` to install project build system, just the `.vsix` file. I should have pull request ready by end of the weekend.

**Comment by beufordy3k** [comment]
@kovalikp 👍👍

**Comment by kovalikp** [comment]
@AArnott could you have a look at https://github.com/kovalikp/nuproj/tree/wip/vs2017? I've been able to construct `NuProj.ProjectSystem.15.vsix` so it copies all files to appropriate folders. The only outstanding issue is that I've lost capability to load resources from registered assembly, so that project name, description and icon are not being applied in New Project dialog. I've got no clue why. Once the project is created, it can produce packages just fine.

You can find result artifacts here:
https://ci.appveyor.com/project/kovalikp/nuproj/build/0.11.30-beta+gba8239254f/artifacts

**Comment by AArnott** [comment]
Cool. Yes, I'll take a look.

**Comment by AArnott** [comment]
@kovalikp : when I compare the pkgdef between the 14 version and the 15 version, I see this:

```diff
  [$RootKey$\Packages\{267c66da-0c67-4933-9ae7-a20c53608e49}] 
  @="NuProjPackage"
  "InprocServer32"="$WinDir$\SYSTEM32\MSCOREE.DLL"
  "Class"="NuProj.ProjectSystem.NuProjPackage"
- "CodeBase"="$PackageFolder$\NuProj.ProjectSystem.14.dll"
+ "Assembly"="NuProj.ProjectSystem.15, Version=0.11.0.0, Culture=neutral, PublicKeyToken=null"
```

Without a codebase, VS can't find the DLL when the CLR wants to load it. Can you fix this difference?

**Comment by kovalikp** [comment]
GOT IT! Had to:
```xml
<UseCodebase>true</UseCodebase>
```

**Comment by kovalikp** [comment]
One last thing. This is just about project in solution.
When referencing `NuProj.Tasks`, project system does not pull dependencies if they com from `project.json`. It works fine when using `packages.config`, so that's why I made `NuProj.Tasks.15`. I've also updated `Microsoft.Build.*` references to latest version. In hindsight, this seems to be unnecessary. Sooo...

- Should I revert it back to single `NuProj.Tasks` project and just replace `project.json` with `packages.config` there?
- Or should I make `NuProj.Dev15.nuproj` package to match `Microsoft.Build.*` in `NuProj.ProjectSystem.15`?
- Or should I just leave as it is and make PR?

**Comment by AArnott** [comment]
I'd prefer we consistently use project.json (or upgrade to VS 2017 PackageReference). There are ways to get msbuild to copy local all the dependencies into the VSIX if that's what you're wondering about. I can share some msbuild snippets I've used for that purpose.

**Comment by AArnott** [comment]
BTW, I had an awful time building your branch. I was amazed AppVeyor was able to figure it out with virtually no instructions. I had to execute several restore commands before things started building. Can you write a script or doc or something on how to do it?

**Comment by kovalikp** [comment]
There is a `build.proj` in the root of the branch. This one is being run by the AppVeyor. I've just purged every bin/obj folder and then execute msbuild without any switches from branch root. But if you provide me with those snippets, I will revert `GenerateProjectSpecificOutputFolder=true` from `binaries.proj` and return the solution closer to original state. Just with updated packages.

**Comment by kovalikp** [comment]
@AArnott could you share those msbuild snippets to include project references from NuGet in the vsix?

**Comment by AArnott** [comment]
Here you go, @kovalikp:

Add this to the projects being referenced (probably through some commonly imported .targets file).

```xml
<Target Name="GetDeployableOutputs"
          DependsOnTargets="ResolveReferences;GetCopyToOutputDirectoryItems;BuiltProjectOutputGroup;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies"
          Returns="@(DeployableOutputs)">
    <ItemGroup>
      <DeployableOutputs Include="
                            @(ReferenceCopyLocalPaths);
                            @(AllItemsFullPathWithTargetPath);
                            @(BuiltProjectOutputGroupOutput->'%(FinalOutputPath)');
                            "
                         Condition=" '%(Extension)' != '.pdb' and '%(Extension)' != '.xml' ">
        <RequiringProjectFullPath>$(MSBuildProjectFullPath)</RequiringProjectFullPath>
        <MSBuildSourceTargetName>GetDeployableOutputs</MSBuildSourceTargetName>
      </DeployableOutputs>
      <DeployableOutputs Include="
                            @(SatelliteDllsProjectOutputGroupOutput);
                            @(SatelliteDllsProjectOutputGroupDependency);
                            "
                         Condition=" '%(SatelliteDllsProjectOutputGroupOutput.WithCulture)' == 'true' or  '%(SatelliteDllsProjectOutputGroupDependency.WithCulture)' == 'true' ">
        <RequiringProjectFullPath>$(MSBuildProjectFullPath)</RequiringProjectFullPath>
        <MSBuildSourceTargetName>GetDeployableOutputs</MSBuildSourceTargetName>
      </DeployableOutputs>
    </ItemGroup>
  </Target>
```

Then to your `ProjectReference` items, add this metadata: 
```xml
<Targets>Build;GetDeployableOutputs</Targets>
```

For my scenario (which isn't quite like yours, but similar) I also added this metadata to the project reference items:

```xml
<OutputItemType>PackagingProjectOutputs</OutputItemType>
```

I then had a target that redirected all such items to the package, in the right locations. But I suspect these last two steps may not be required for your case.

**Comment by kovalikp** [comment]
Thanks. Hopefully I find some spare time to integrate it soon(ish).

**Comment by kovalikp** [comment]
So, VSSDK build system excludes MSBuild and NuGet packages implicitly. Extension works just fine without them. I've created a PR  for @AArnott to review. For those who cannot wait, you can try download `NuProj.ProjectSystem.15.vsix` from CI build here: https://ci.appveyor.com/project/kovalikp/nuproj/build/artifacts

**Comment by beufordy3k** [comment]
Ok, so I've had an opportunity to try this out with a fresh solution and projects. Things are coming along nicely and a number of the minor annoyances compared to the previous version are fixed. Huzzah!

There still seems to be some work needed... as per below.

I'm using VS 2017 Enterprise,

```
Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.10 D15RTWSVC
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise
```
Installation of the extension and creation of some new .nuproj projects went off without a hitch.

I created a brand new solution with four new projects.
- Solution
  - `OtherLib` (*.NET 4.6.2 Class Library*)
  - `Sample.Package` (*.NET 4.6.2 Class Library*)
  - `OtherLib.Nuget` (*nuproj project*)
  - `Sample.Package.Nuget` (*nuproj project*)

Sample solution here: [https://github.com/beufordy3k/nuproj-sample-library](https://github.com/beufordy3k/nuproj-sample-library)

I installed the updated NuProj and NuProj.Common (`0.11.33-beta-g3fe44656b1`) nuget packages from a local feed into my class libraries.

When I attempted to build, I received the following:
```
The "AssignTargetFramework" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at NuProj.Tasks.AssignTargetFramework.ConvertToPackageFile(ITaskItem output)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuProj.Tasks.AssignTargetFramework.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

So I enabled fusion log binding and there is a failure when attempting to locate the `Microsoft.CodeAnalysis.CSharp` assembly. 
See attached file:
[Microsoft.CodeAnalysis.CSharp.resources, Version=2.0.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35.txt](https://github.com/nuproj/nuproj/files/877939/Microsoft.CodeAnalysis.CSharp.resources.Version.2.0.0.0.Culture.en.PublicKeyToken.31bf3856ad364e35.txt)

It appears that this assembly used to ship next to msbuild in v14 but is no longer present in the new v15 msbuild that comes with VS 2017.

I did find this issue in the msbuild github repo, [https://github.com/Microsoft/msbuild/issues/1183](https://github.com/Microsoft/msbuild/issues/1183) that seems like it's at least tangentially related.

Please let me know if I can provide any more detail or if there's a workaround/fix/something missing already for this.

Looking forward to this next release. Thanks!

**Comment by beufordy3k** [comment]
@AArnott @kovalikp any more progress on this? anything I can do to test/help out?

**Comment by kovalikp** [comment]
I should have time to look at this over the weekend. I'm assuming you don't have any other version of VS installed on this machine?

**Comment by beufordy3k** [comment]
@kovalikp I actually have both VS 2015 Enterprise and VS 2017 Enterprise installed.

**Comment by jamesharling** [comment]
I'm getting the same issue as @beufordy3k on a copy of VS 2017 Professional:

`System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.`

This was using the latest artifacts from AppVeyor, commit `2696627b`.

**Comment by AndyCJ** [comment]
I'm seeing this error for the same commit (`2696627b`) as @jamesharling.

Like @beufordy3k, I also have VS2015 installed.

**Comment by AndyCJ** [comment]
I found this issue on the NuGet github site which seems to be relevant: https://github.com/NuGet/Home/issues/5242

It talks about VS 2017 Update 3 updating the assembly version to 4.3, the exception message says it's looking for version 4.0, and the issue says that `devenv.exe.config` doesn't have the assembly binding redirects to make it work (and they won't be added).

I'm still on VS2017 Update 2 as Update 3 is still pre-release, so I went digging to check out where I can find `NuGet.Frameworks.dll` on my local drive, and what versions they are.

`4.0.0.0` - `C:\Program Files (x86)\MSBuild\NuProj`
`4.2.0.0` - `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet`

Interestingly, `C:\Program Files (x86)\MSBuild\NuProj` has multiple `NuGet.*.dll` files, but `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\NuProj` has none.

There are many other instances of it on my drive, but they seem to either be for other situations (.net core, sdk installations) or other languages.

I then enabled the fusion logging to see what VS was trying to bind to when building the NuProj project. It was looking in two locations:

`C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/`
`C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/NuProj/`

I checked both those folders (and their sub-folders) and there was no `NuGet.Frameworks.dll` to be found.

**Comment by AArnott** [comment]
@kovalikp  is this something you want to follow up on and fix?

**Comment by ackphht** [comment]
Just wanted to mention that I was able to get this working for VS2017, in case it helps anyone else.

I downloaded the vsix package from the CI server per [this comment](https://github.com/nuproj/nuproj/pull/286#issuecomment-319782855). After installing it, I started getting the error mentioned above for "Could not load file or assembly 'NuGet.Frameworks, Version=4.0.0.0". I turned on fusion logging and worked through the missing DLLs. By downloading the v4.0.0 nuget packages and extracting/adding the following DLLs to my "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\NuProj" folder, I was able to get my .nupkg files:

* NuGet.Frameworks.dll
* NuGet.Packaging.Core.dll
* NuGet.Packaging.Core.Types.dll
* NuGet.Packaging.dll
* NuGet.Versioning.dll

I see in the vsix package, there's a $MSBuild folder that seems to be what gets put into the MSBuild\NuProj folder. Maybe those DLLs just need to be included in there?

and thanks for the work on this project; it is a very useful one.

**Comment by kovalikp** [comment]
I've finally got some time to look at this again over the weekend. Just getting unit test working under VS2017 build system is little bit more complicated than I expected. So, work in progress...

**Comment by michaelkollmann** [comment]
It's been a month. Any updates?

**Comment by submatrixpxq** [comment]
Any updates ?

**Comment by Pzixel** [comment]
We have to have some way to open one single project from 2015 and 2017 studio. Now it's not possible and it's frustrating.

**Comment by dparkar** [comment]
Same requirement here. A NuProj Project will not load in VS2017. Appreciate the work !

**Comment by AArnott** [comment]
Published as https://marketplace.visualstudio.com/items?itemName=NuProjTeam.NuProj2017

**Comment by Pzixel** [comment]
@AArnott 404

**Comment by AArnott** [comment]
You're right, @Pzixel. It wasn't marked "public". Thanks. I've fixed that.

**Comment by dmalanij** [comment]
Unfortunately, is not working. At least not for me in 2 different computers. Even if nuproj files open correctly, when building they fail with 
```
MSB4018	The "AssignTargetFramework" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. El sistema no puede encontrar el archivo especificado.
File name: 'NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at NuProj.Tasks.AssignTargetFramework.ConvertToPackageFile(ITaskItem output)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuProj.Tasks.AssignTargetFramework.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```
And the source points to 

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\NuProj\NuProj.targets	376	
```

This is happening in a computer where NUPROJ for VS2015 used to work fine.  Is there any special prerequisite for this version?

I'll try to take a look with more detail later as well as trying it out on a third computer.

**Comment by AArnott** [comment]
I'm sorry to hear that, @dmalanij. Can you open a new issue to track this one? Hopefully @kovalikp  will know what's going on.
