### ISSUE TITLE
Unable to restore with Nuget 3.5

### ISSUE THREAD

**Issue by petero-dk** [nuproj/nuproj#269]
We are using Visual Studio Online to build our packages. Additionally they are hosted on VSO. We have followed the instructions here:
https://github.com/nuproj/nuproj/blob/master/docs/Build.md

However Nuget 3.5 does a project analysis for all projects that contain a project.json file. The .nuproj files does not live up to this and will fail spectacularly with missing targets for all sorts of things. 

Most of the errors could be removed by adding conditions on the NuProj Targets. The final error I could not remove was:

```
The target "_NuGet_GetProjectsReferencingProjectJsonInternal" does not exist in the project
```

THE SOLUTION IS SIMPLE:

Instead of using the project based project.json, instead create a folder called .nuget in the solution directory, and in that folder add a packages.config file.

The contents of that file should be:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="NuProj" version="0.11.17-beta" developmentDependency="true" />
</packages>
```

Based on nuget documentation the solution packages.config file is read first (https://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#restore) see bullet # 4 (When nuget is restoring packages for a solution, nuget takes the following steps) and notice that the first restore is the solution file.

**Comment by AArnott** [comment]
I've hit similar issues, and so far I've solved it by running `nuget restore project.json` on the nuproj's project.json directly first, then running it on the solution. But if your approach reduces that two-step process to just one, that sounds worthwhile. :)

**Comment by petero-dk** [comment]
It does seem to work quite well, but possibly this is only with the Nuget beta. 

I just realized I have selected Nuget version 3.5.5 in Visual Studio Online. With that setup, it is plug and play. 

But as for Nuget 3.3 (current release) it might not actually work 
* NuGet/Home#522
* NuGet/Home#1521

**Comment by AArnott** [comment]
Thanks again for your contribution!

**Comment by petero-dk** [comment]
Np - thanks for a great tool!
