### ISSUE TITLE
"Project (incompatible)"/"The project type is not supported by this installation." after reinstall.

### ISSUE THREAD

**Issue by AndyCJ** [nuproj/nuproj#273]
I installed the NuProj extension sometime earlier this year.
Recently I noticed there was a new version out so I installed the newer version.
After installing the new version I noticed that my NuProj projects in an existing solution were now failing to load with a message of "(incompatible)".

![nuproj 1](https://cloud.githubusercontent.com/assets/855867/20061769/32b5975e-a4f9-11e6-8377-43fa2040e023.png)

I checked that NuProj was installed by looking at the VS about window, and it appeared in the list.

![nuproj 2](https://cloud.githubusercontent.com/assets/855867/20061797/4b7d0042-a4f9-11e6-9707-5b0115e1362f.png)

I tried uninstalling, and then reinstalling NuProj (with a reboot after the uninstall and the reinstall just to be sure) and that made no difference.

I then tried creating a new NuProj project in a new solution.

![nuproj 3](https://cloud.githubusercontent.com/assets/855867/20061898/a0479dc6-a4f9-11e6-9856-e79a349663fb.png)

But I ended up getting a similar error in a dialog.

![nuproj 4](https://cloud.githubusercontent.com/assets/855867/20061916/b750d5be-a4f9-11e6-921d-0dafa43d1db5.png)

I am able to successfully install the same version of NuProj on other machines, so it would appear that the uninstall process isn't removing whatever has caused this issue.

Is there a way to "fully" clean out the NuProj install? Or otherwise get NuProj working again?

**Comment by kovalikp** [comment]
Could you try clean VS MEF component cache first? It should be located in `%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache`.

**Comment by AndyCJ** [comment]
That worked!

Thanks a lot kovalikp.
