### ISSUE TITLE
Release update to NuProj on NuGet

### ISSUE THREAD

**Issue by AlexEyler** [nuproj/nuproj#287]
There have been quite a few updates to nuproj since the last release (0.11.14-beta), including a fix for a bug that blocks NuProj from working on MSBuild 14.0+ (#257). Are there any plans to release a new version to nuget.org? Or is there a different release vehicle that I'm unaware of?

**Comment by AndyCJ** [comment]
I think everyone is currently distracted trying to figure out VS2017 support: https://github.com/nuproj/nuproj/issues/266

And if it's even worth carrying on with nuproj: https://github.com/nuproj/nuproj/issues/282

**Comment by beufordy3k** [comment]
@AndyCJ Any update on with path forward regarding, (https://github.com/nuproj/nuproj/issues/266) or (https://github.com/nuproj/nuproj/issues/282)

**Comment by AndyCJ** [comment]
@beufordy3k I don't have any more information sorry, I just read those tickets and pointed it out to AlexEyler.

**Comment by AArnott** [comment]
Done. It's 0.11.28-beta.
