### ISSUE TITLE
target multiple frameworks in a single nuget package

### ISSUE THREAD

**Issue by quezlatch** [nuproj/nuproj#288]
I'm pretty sure i'm missing something obvious, but I want to target multiple frameworks in a single nuget package.
* Is this possible?
* Do I create a project for framework and just reference it?
* Would this handle the framework groups, dependencies, etc?

Thanks

**Comment by AArnott** [comment]
Yes, you can target multiple frameworks. Just have multiple project references, each to a project that targets a different framework. If you're using packages.config, the dependencies will be all written out for you automatically.

caveats: It doesn't pick up PackageReference or project.json dependencies automatically. And it doesn't work with the new .NET SDK multi-targeting projects. However, @kovalikp's recent work to add VS2017 support in NuProj might have improved support in these areas.

**Comment by quezlatch** [comment]
many thanks. that's worked perfectly!
