### ISSUE TITLE
Template is not available in Visual Studio 2019

### ISSUE THREAD

**Issue by ErikApption** [nuproj/nuproj#307]
I was able to install the extension without any issues but the template is not showing up in the new project wizard...

**Comment by RonenGlants** [comment]
Is there a way to support nuproj in VS 2019?

**Comment by AArnott** [comment]
Sure. But the current owners including myself are not interested in taking this project forward.

**Comment by ndrwrbgs** [comment]
@AArnott I'm sure it exists somewhere and I just haven't found it yet, but what is the suggestion for folks depending on this to move forward? Should we be replacing nuproj with another feature? Any chance there are guides for doing that?

**Comment by AArnott** [comment]
If you must continue using nuproj but lack of its continued development is getting to you, you can fork it and take it forward. 
We haven't written migration guides. Here's the guidance I follow though:

1. blow away the nuproj from your repo.
1. create or update your csproj to pack itself
1. compare the resulting nuspec from before and after the change and fiddle with csproj until it meets your needs.

There is ample documentation for csproj self-packing projects that NuGet/Microsoft publishes.
