### ISSUE TITLE
Nuget packages not identified as dependency when using PackageReference

### ISSUE THREAD

**Issue by AleRoe** [nuproj/nuproj#308]
I'm using Nuproj to package a ClassLibrary project (VS2017)
The ClassLibrary references a singe Nuget package.
The ClassLibrary uses PackageReference instead of Packages.config.

When building the Nuget package, the external package reference is not identified as a dependency. Instead, all the DLLs from the external package are copied into the package.

If I build the same project using Packages.config in the ClassLibrary, the external Nuget package is correctly recognized as a dependency.

**Comment by AArnott** [comment]
NuProj is no longer under active development. It supported a packages.config world. With PackageReference and self-packing projects, NuProj is hardly necessary any more.
