### ISSUE TITLE
Can't suppress certain reference assemblies from inclusion in nupkg

### ISSUE THREAD

**Issue by AArnott** [nuproj/nuproj#31]
It seems when I include a particular project reference from nuproj to one of my class libraries, all that libraries dependency assemblies get included in the NuGet package. I can't allow this because I don't have a redist license for them. 

Besides, the package doesn't need to include these assemblies because at design-time/build-time they're not necessary. At runtime they arguably _might_ be necessary, but at runtime all this is running within an app that already has these assemblies so it's a non-issue.

But I don't see a way in NuProj to selectively exclude assemblies (or just turn off this transitive search behavior).

**Comment by chandramouleswaran** [comment]
How about using the "Copy Local" property (or the <Private> node under <ProjectReference>)? This might be an update to the Nuproj.targets file?
