### ISSUE TITLE
NuProj package does not contain the Rules folder that the VS extension contains

### ISSUE THREAD

**Issue by BloodKroll** [nuproj/nuproj#61]
Was running into a problem on a TFS build server using the NuProj package restore and the Rules folder was not showing up in the NuProj package folder. Also, appears that the default location for the NuProj was the extension folder and not the packages folder. I copied the Rules folder from the extension installation folder to the NuProj packages tools folder and now the project is loading in visual studio

**Comment by terrajobst** [comment]
This has been fixed now because we've merged the VS integration into master.

**Comment by AArnott** [comment]
Although the .targets in the nupkg now point to the Rules folder files, the Rules folder itself is still absent.
