### ISSUE TITLE
Override `TargetFramework` for `ProjectReference` items

### ISSUE THREAD

**Issue by kovalikp** [nuproj/nuproj#64]
While working on #26, I've run into potential issue. NuGet reference allows to use framework specific sub-directories for `tools` and `build` directories. In #63 this is default behavior, but I think it would be good to allow user to suppress or override the behavior.

```xml
<ItemGroup>
  <ProjectReference Include="..\Tool\Tool.csproj">
    <PackageDirectory>Tools</PackageDirectory>
    <TargetFramwork>???</TargetFramwork>
  </ProjectReference>
</ItemGroup>
```
`???` could be either empty (default behavior), `None` to put output directly into `tools` folder, or short form framework name to override auto detection.

Thoughts?

**Comment by bhugot** [comment]
I totally agree on this.

**Comment by kovalikp** [comment]
There are two special for target framework, auto-detect (currently default behavior) and `any` target framework (empty string in nuspec). We should decide, what would be metadata value for those.

I think it would be best to define `AutoDetect` or `Unknown` via `ItemDefinitionGroup`. For `any` target framework use empty string to make it consistent with nuspec files.

For example:
```xml
<ItemDefinitionGroup>
  <ProjectReference>
    <PackageDirectory>Libraries</PackageDirectory>
    <TargetFramework>AutoDetect</TargetFramework>
  </ProjectReference>
</ItemDefinitionGroup>

<ItemGroup>
  <ProjectReference Include="..\Tool\Tool.csproj">
    <PackageDirectory>Tools</PackageDirectory>
    <TargetFramework></TargetFramework>
  </ProjectReference>
</ItemGroup>
```

**Comment by AArnott** [comment]
@kovalikp This sounds pretty good. #63 has been merged. Can you prepare a pull request for this?
When you add metadata to the reference, can you also describe that metadata as I described `PackageDirectory` in 0ca627dc824a39dc580a89ad911b1f76375cef1c so that the user can set this metadata within VS?

**Comment by kovalikp** [comment]
Regarding the VS integration, any idea how to deal with portable libraries? I don't think listing all possible combinations is viable strategy. Or is it? :wink:

For reference, this is the list I've found:

Profile # | Name
--- | ---
Profile5 | .NET Portable Subset (.NET Framework 4, Windows 8)
Profile6 | .NET Portable Subset (.NET Framework 4.0.3, Windows 8)
Profile7 | .NET Portable Subset (.NET Framework 4.5, Windows 8)
Profile14 | .NET Portable Subset (.NET Framework 4, Silverlight 5)
Profile19 | .NET Portable Subset (.NET Framework 4.0.3, Silverlight 5)
Profile24 | .NET Portable Subset (.NET Framework 4.5, Silverlight 5)
Profile31 | .NET Portable Subset (Windows 8.1, Windows Phone Silverlight 8.1)
Profile32 | .NET Portable Subset (Windows 8.1, Windows Phone 8.1)
Profile37 | .NET Portable Subset (.NET Framework 4, Silverlight 5, Windows 8)
Profile42 | .NET Portable Subset (.NET Framework 4.0.3, Silverlight 5, Windows 8)
Profile44 | .NET Portable Subset (.NET Framework 4.5.1, Windows 8.1)
Profile47 | .NET Portable Subset (.NET Framework 4.5, Silverlight 5, Windows 8)
Profile49 | .NET Portable Subset (.NET Framework 4.5, Windows Phone Silverlight 8)
Profile78 | .NET Portable Subset (.NET Framework 4.5, Windows 8, Windows Phone Silverlight 8)
Profile84 | .NET Portable Subset (Windows Phone 8.1, Windows Phone Silverlight 8.1)
Profile92 | .NET Portable Subset (.NET Framework 4, Windows 8, Windows Phone 8.1)
Profile102 | .NET Portable Subset (.NET Framework 4.0.3, Windows 8, Windows Phone 8.1)
Profile111 | .NET Portable Subset (.NET Framework 4.5, Windows 8, Windows Phone 8.1)
Profile136 | .NET Portable Subset (.NET Framework 4, Silverlight 5, Windows 8, Windows Phone Silverlight 8)
Profile147 | .NET Portable Subset (.NET Framework 4.0.3, Silverlight 5, Windows 8, Windows Phone Silverlight 8)
Profile151 | .NET Portable Subset (.NET Framework 4.5.1, Windows 8.1, Windows Phone 8.1)
Profile157 | .NET Portable Subset (Windows 8.1, Windows Phone 8.1, Windows Phone Silverlight 8.1)
Profile158 | .NET Portable Subset (.NET Framework 4.5, Silverlight 5, Windows 8, Windows Phone Silverlight 8)
Profile225 | .NET Portable Subset (.NET Framework 4, Silverlight 5, Windows 8, Windows Phone 8.1)
Profile240 | .NET Portable Subset (.NET Framework 4.0.3, Silverlight 5, Windows 8, Windows Phone 8.1)
Profile255 | .NET Portable Subset (.NET Framework 4.5, Silverlight 5, Windows 8, Windows Phone 8.1)
Profile259 | .NET Portable Subset (.NET Framework 4.5, Windows 8, Windows Phone 8.1, Windows Phone Silverlight 8)
Profile328 | .NET Portable Subset (.NET Framework 4, Silverlight 5, Windows 8, Windows Phone 8.1, Windows Phone Silverlight 8)
Profile336 | .NET Portable Subset (.NET Framework 4.0.3, Silverlight 5, Windows 8, Windows Phone 8.1, Windows Phone Silverlight 8)
Profile344 | .NET Portable Subset (.NET Framework 4.5, Silverlight 5, Windows 8, Windows Phone 8.1, Windows Phone Silverlight 8)

**Comment by AArnott** [comment]
I think those `Profile*` names don't cover all scenarios and I *think* they won't be expanded in the future. Regardless, I don't think we should list them all here, but rather use EnumValue's for each of your other options of default and any. The user can explicitly type in other options that they want.

**Comment by kovalikp** [comment]
Obsolete. It's possible to use `TargetSubdirectory` metadata to customize how to package project output.
