### ISSUE TITLE
Indirect NuGet dependencies are not included in the resulting NuGet package.

### ISSUE THREAD

**Issue by williamb1024** [nuproj/nuproj#71]
Assume the following project layout:

- `Project A` (CSharp)
  - References:
    - Project B
    - NuGet Package A
  - Produces:
    - Assembly A
- `Project B` (CSharp)
  - References:
    - NuGet Package B
      - Contains:
        - Assembly NuGet-B
  - Produces:
    - Assembly B
- `Project C` (NuProj)
  - References:
    - Project A
  - Produces:
    - NuGet Package C

Building `Project C` produces the following package:
- NuGet Package C
  - lib
    - Assembly A
    - Assembly B
  - Dependencies:
    - NuGet Package A

I believe, `NuGet Package C` should contain a dependency on `NuGet Package B` or contain `Assembly NuGet-B`. Currently, the resulting package has neither.

A simple workaround at the moment is to reference `Project B` from `Project C`, which then causes `NuGet Package B` to be a direct reference rather than indirect.

I cannot think of a good reason to not include indirect NuGet package references. Am I missing something important?

**Comment by nickform** [comment]
I have read your issue several times and think that you have overlooked some of the power of a well-designed package management system.

The package manager is responsible to get your dependencies _and their dependencies_ (recursively). Unless the assemblies created by `Project C` depend directly on `Assembly NuGet-B`, it would be incorrect for `NuGet Package C` to state that it depends on `NuGet Package B`.

Consider the scenario that a new version of `NuGet Package A` is released which drops its dependency on `NuGet Package B`. After upgrading `Project C` to this version (and bear in mind that NuGet 3 allows you to specify your dependency such that you always restore the latest) the reference to `NuGet Package B` is now completely superfluous. To me this is a sign that it was the wrong thing to do in the first place.

The suggestion that `NuGet Package C` should contain `Assembly NuGet-B` is even worse: now you have to publish a new version of the former for every new version of the latter which you need and this totally nullifies one of the main benefits of a package manager.

Apologies If I have misunderstood you. If so, perhaps you could attach some example project.json and *.NuSpec files to illustrate?

**Comment by AArnott** [comment]
You menII
