### ISSUE TITLE
TFS Built with NuProj Nuget Package

### ISSUE THREAD

**Issue by chroustm** [nuproj/nuproj#74]
I really like the idea behind NuProj and I really appreciate the work but...
I was unable to get a successful TFS Build with Version 0.9.3-beta of the NuProj Nuget Package. 
1. The package is missing the "Rules" directory (and the XML Files)
2. During the build the "_NuProjGetProjectClosure" target is called which itself calls all referenced packages with the target "_NuProjGetProjectClosure". This does not work since the TFS does not have the "Microsoft.Common.NuProj.targets" in its "ImportAfter" folder.

I ended up creating my own private slightly modified NuProj NuGet Package with a Rules Folder and a "_NuProjGetProjectClosure" target that does not build the referenced projects...

**Comment by terrajobst** [comment]
> The package is missing the "Rules" directory (and the XML Files)

That's interesting. I'll try to repro this.

> During the build the "_NuProjGetProjectClosure" target is called which itself calls all referenced packages with the target "_NuProjGetProjectClosure". This does not work since the TFS does not have the "Microsoft.Common.NuProj.targets" in its "ImportAfter" folder.

When you rely on NuProj being restored as a NuGet package, i.e. not having the MSI installed, you need to follow the steps [here](https://github.com/terrajobst/nuproj/blob/master/docs/Build.md). Specifically, you need to pass the following properties into your build:

```xml
<PropertyGroup>
    <MyNuProjPath>$(MyCheckinRoot)packages\NuProj.0.9.3\tools\</MyNuProjPath>
    <NuProjTargetsPath>$(MyNuProjPath)NuProj.targets</NuProjTargetsPath>
    <!-- This is required in order to get access to indirect dependencies.
         If you're already having a custom targets file that you inject
         into Microsoft.Common.targets, omit this line and instead import
         Microsoft.Common.NuProj.targets into your targets file. -->
    <CustomAfterMicrosoftCommonTargets>$(MyNuProjPath)Microsoft.Common.NuProj.targets</CustomAfterMicrosoftCommonTargets>
</PropertyGroup>
```

**Comment by BenStull** [comment]
Looks like the documentation [on github](https://github.com/terrajobst/nuproj/blob/master/docs/Build.md) is not in sync with the documentation [on your site](http://nuproj.net/documentation/#checked-in-toolkit).

This bit me for quite a while until I found the instructions to add the Microsoft.Common.NuProj.targets reference for TFS integration.

**Comment by chroustm** [comment]
I was finally able to try the suggested configuration but could not really get it to work without an error. I have to admit that I'm quite a newbe with MSBuilt so maybe I'm missing something here.
 
I added the "CustomAfterMicrosoftCommonTargets" property to my project. But the property did not propagate to the builds of the referenced projects. This seems to be due to the "_NuProjGetProjectClosure" target calling the task MSBuild and passing the properties that where added to "ProjectProperties". "ProjectProperties" only contains "Configuration" and "Platform" so my "CustomAfterMicrosoftCommonTargets" does not get propagated to the build of the referenced projects. 

When I add "CustomAfterMicrosoftCommonTargets" to "ProjectProperties" I do not get any build errors...

**Comment by kovalikp** [comment]
This is resolved here: https://github.com/kovalikp/nuproj/commit/28cca860ba05b4baf702cac152f2c76efe03e707

**Comment by AArnott** [comment]
@chroustm The missing Rules folder shouldn't cause any issue with build. It's only looked at by Visual Studio and even then, not for purposes of Build. I'm guessing you didn't actually see an error on this outside of VS. Is that right?

Anyway, the next release of NuProj.nupkg should include the Rules folder for a better VS integration experience.

**Comment by AArnott** [comment]
@kovalikp ...and unresolved with 69dded6e, since it introduced #118

**Comment by kovalikp** [comment]
I think we can close this with #128 for now. If NuGet expands  support for CPS, we might be able to merge NuProj.Common into NuProj package.
