### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by AndirNotes** [nuproj/nuproj#84]
I see that last developer activity was more than 1 month ago, 8 pull requests are waiting something and no comments from the author... 
I want to use it in our production development cycle, but that inactivity and author's silence scares me a little. 

P.S. also the VS extension is not open-sourced at all.

**Comment by AArnott** [comment]
I expect the project author is just very busy. I'll ping him.
We'd like to open source the VS extension but are waiting for the project system on which it is based to be documented.

**Comment by AndirNotes** [comment]
Good to hear, because the project and VS extension are really helpful for package creation.

**Comment by AArnott** [comment]
The author is still interested in this project, but very busy at the moment. I am tempted to start merging pull requests into my fork of the project (in fact, I already have) in a more pseudo-official capacity till @terrajobst is back.

**Comment by kovalikp** [comment]
@AArnott, how about asking @terrajobst to add you as a collaborator, so you can merge stuff directly into the master ;)

**Comment by AArnott** [comment]
Already done. 😃 

Sent from my Windows Phone

-----Original Message-----

**Comment by williamb1024** [comment]
@AArnott Are you starting to handle the outstanding pull requests?

**Comment by AArnott** [comment]
Yes. Immo has so empowered me. But first, we're going to meet once to go
over some pull requests together and make sure I represent his interests
well.

**Comment by terrajobst** [comment]
> I see that last developer activity was more than 1 month ago, 8 pull requests are waiting something and no comments from the author... 

Sorry for the inactivity. As @AArnott explained I was quite busy at work. As you can see, @AArnott and myself created this organization so that more folks can run this project so we don't bottleneck on a single person, AKA me.

We'll review some of the pending PRs later today.
