### ISSUE TITLE
Wildcard Versions should be supported

### ISSUE THREAD

**Issue by piotrpMSFT** [nuproj/nuproj#87]
Visual Studio allows for automatic versioning of assemblies by using a '1.0.*' version number. This causes the build and revision portions of the version number to be computed at build time and always incrementing.

NuGet Pack, when ran against a csproj, can read the version number of the project. Combined with the previously mentioned feature, this results in each build producing a uniquely named & versioned NuGet package.

It would be wonderful if NuProj files directly supported a similar wildcard-enabled version number.

**Comment by terrajobst** [comment]
I think this would be covered by #20.
