### ISSUE TITLE
Installing 0.9.3 in VS2013 does not create NuGet project type

### ISSUE THREAD

**Issue by jehrenzweig** [nuproj/nuproj#89]
http://nuproj.net/documentation/#checked-in-toolkit

I installed 0.9.3 via NuGet, restarted VS2013 for good measure, then tried to look for the new "NuGet Package" project template.  However, I wasn't able to find it... is there somewhere else I should be looking?

**Comment by AArnott** [comment]
NuGet doesn't install templates. If you want VS templates, install the NuProj MSI from http://nuproj.net
