### ISSUE TITLE
Cannot build NuProj solution on localhost

### ISSUE THREAD

**Issue by kovalikp** [nuproj/nuproj#92]
I'm getting `Could not load file or assembly '...\nuproj\lib14\Xaml2Cs.exe' or one of its dependencies.` error when I try to build the project.
Can you add `Microsoft.Build.Framework, Version=14.0.0.0` and `Microsoft.Build.Utilities.Core, Version=14.0.0.0` to lib14 folder?

Due to reasons, I don't want to install VS2015 CTP yet.

**Comment by AArnott** [comment]
I don't know that we can legally check in those Microsoft assemblies. Can you get by with a partial build?

**Comment by kovalikp** [comment]
Isn't that already open sourced? I thought it's just a older build of https://github.com/Microsoft/msbuild.

**Comment by AArnott** [comment]
No. I'm sorry to say that what was open sourced is not the same thing.

**Comment by kovalikp** [comment]
Ok, never mind. I'll try to make a build just for VS2013. It will probably need separate .sln and .wixproj files, but should not be hard.

**Comment by AArnott** [comment]
While I can understand you not wanting to install a Visual Studio beta, have you considered simply installing [MSBuild 14](http://www.microsoft.com/en-us/download/details.aspx?id=44931)? That's a 20MB footprint and won't destabilize your computer.

**Comment by kovalikp** [comment]
This is actually much better idea :+1: . But I'm still missing following assemblies:

Microsoft.VisualStudio.ImageCatalog, Version=14.0.0.0
Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime
Microsoft.VisualStudio.ProjectSystem.Utilities.v14.0
Microsoft.VisualStudio.ProjectSystem.V14Only
Microsoft.VisualStudio.ProjectSystem.VS.V14Only
Microsoft.VisualStudio.Validation, Version=14.0.0.0

**Comment by AArnott** [comment]
Ah, that's true. At least we know it's a temporary issue (since VS2015 will release eventually). In the meantime ya, I guess if you don't want to install the prerelease version, a bit of local changes on your box to the solution may be required.

**Comment by kovalikp** [comment]
One more issue: lib\Xaml2Cs.exe is delay-signed. Please check in a correctly signed one, if you can.

**Comment by AArnott** [comment]
Whoops. Ya... I'll get on that.
